package dev.s7a.sqldelight.oracle.dialects.oracle

import app.cash.sqldelight.core.SqlDelightCompilationUnit
import app.cash.sqldelight.core.SqlDelightDatabaseName
import app.cash.sqldelight.core.SqlDelightDatabaseProperties
import app.cash.sqldelight.core.SqlDelightEnvironment
import app.cash.sqldelight.core.SqlDelightSourceFolder
import app.cash.sqldelight.core.annotators.OptimisticLockCompilerAnnotator
import app.cash.sqldelight.core.lang.MigrationLanguage
import app.cash.sqldelight.core.lang.SqlDelightLanguage
import app.cash.sqldelight.core.lang.SqlDelightQueriesFile
import com.alecstrong.sql.psi.core.SqlAnnotationHolder
import com.intellij.lang.LanguageParserDefinitions
import com.intellij.psi.PsiDocumentManager
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import java.io.File
import java.nio.file.Files

class OracleParserBackedTest :
    FunSpec({
        test("parses Oracle create table type names through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE sample (
                  id NUMBER(10) NOT NULL,
                  amount NUMBER(10, 2),
                  name NATIONAL CHARACTER VARYING(100),
                  payload JSON,
                  raw_uuid RAW(16),
                  embedding VECTOR(3, FLOAT32),
                  created_at TIMESTAMP(6) WITH LOCAL TIME ZONE,
                  elapsed INTERVAL DAY TO SECOND
                );

                selectAll:
                SELECT id, amount, name, payload, raw_uuid, embedding, created_at, elapsed
                FROM sample;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle inline column constraints through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE accounts (
                  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                  external_id VARCHAR2(64) CONSTRAINT accounts_external_id_unique UNIQUE ENABLE NOVALIDATE,
                  status VARCHAR2(16) DEFAULT 'ACTIVE' NOT NULL,
                  archived_at TIMESTAMP INVISIBLE,
                  parent_id NUMBER REFERENCES accounts(id) DEFERRABLE INITIALLY DEFERRED
                );

                selectAll:
                SELECT id, external_id, status, archived_at, parent_id
                FROM accounts;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle table constraints through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE account_events (
                  account_id NUMBER NOT NULL,
                  event_id NUMBER NOT NULL,
                  parent_event_id NUMBER,
                  event_type VARCHAR2(64) NOT NULL,
                  event_payload JSON,
                  CONSTRAINT account_events_pk PRIMARY KEY (account_id, event_id) ENABLE,
                  CONSTRAINT account_events_type_unique UNIQUE (account_id, event_type) DEFERRABLE INITIALLY IMMEDIATE,
                  CONSTRAINT account_events_payload_check CHECK (event_payload IS NOT NULL) NOVALIDATE,
                  CONSTRAINT account_events_parent_fk FOREIGN KEY (account_id, parent_event_id) REFERENCES account_events(account_id, event_id) DEFERRABLE INITIALLY DEFERRED
                );

                selectAll:
                SELECT account_id, event_id, parent_event_id, event_type, event_payload
                FROM account_events;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create table statement variants through SQLDelight environment exactly") {
            val sql =
                """
                CREATE GLOBAL TEMPORARY TABLE IF NOT EXISTS staged_accounts (
                  account_id NUMBER NOT NULL,
                  external_id VARCHAR2(64),
                  CONSTRAINT staged_accounts_pk PRIMARY KEY (account_id)
                ) ON COMMIT PRESERVE ROWS;

                CREATE PRIVATE TEMPORARY TABLE private_staged_accounts (
                  account_id NUMBER NOT NULL,
                  external_id VARCHAR2(64)
                ) ON COMMIT DELETE ROWS;

                CREATE TABLE account_snapshot AS
                SELECT account_id, external_id
                FROM staged_accounts;

                selectAll:
                SELECT account_id, external_id
                FROM account_snapshot;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle alter table statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE alter_targets (
                  id NUMBER PRIMARY KEY,
                  status VARCHAR2(16)
                );

                ALTER TABLE alter_targets ADD created_at TIMESTAMP;
                ALTER TABLE alter_targets ADD (
                  updated_at TIMESTAMP,
                  archived_at TIMESTAMP INVISIBLE
                );
                ALTER TABLE alter_targets ADD CONSTRAINT alter_targets_status_check CHECK (status IS NOT NULL) ENABLE;
                ALTER TABLE alter_targets MODIFY (
                  created_at TIMESTAMP NOT NULL,
                  updated_at TIMESTAMP NOT NULL
                );
                ALTER TABLE alter_targets MODIFY status VARCHAR2(32) NOT NULL;
                ALTER TABLE alter_targets RENAME COLUMN status TO account_status;
                ALTER TABLE alter_targets DROP COLUMN archived_at CASCADE CONSTRAINTS;
                ALTER TABLE alter_targets DROP COLUMN created_at CASCADE CONSTRAINTS;
                ALTER TABLE alter_targets DROP CONSTRAINT alter_targets_status_check;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create index statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE indexed_accounts (
                  id NUMBER PRIMARY KEY,
                  status VARCHAR2(32) NOT NULL,
                  created_at TIMESTAMP,
                  archived_at TIMESTAMP
                );

                CREATE UNIQUE INDEX IF NOT EXISTS indexed_accounts_status_idx
                ON indexed_accounts (status) VISIBLE ONLINE;

                CREATE BITMAP INDEX indexed_accounts_archive_idx
                ON indexed_accounts (archived_at, created_at) INVISIBLE NOLOGGING;

                CREATE INDEX indexed_accounts_created_idx
                ON indexed_accounts (created_at DESC) REVERSE COMPUTE STATISTICS;

                CREATE INDEX indexed_accounts_status_upper_idx
                ON indexed_accounts (UPPER(status));

                selectAll:
                SELECT id, status, created_at, archived_at
                FROM indexed_accounts;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create view statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE view_accounts (
                  id NUMBER PRIMARY KEY,
                  status VARCHAR2(32) NOT NULL,
                  created_at TIMESTAMP
                );

                CREATE OR REPLACE FORCE EDITIONING VIEW account_status_view AS
                SELECT id AS account_id, status AS account_status, created_at AS account_created_at
                FROM view_accounts
                WHERE status IS NOT NULL
                BEQUEATH CURRENT_USER
                WITH CHECK OPTION;

                CREATE NO FORCE VIEW readonly_account_view AS
                SELECT id, status
                FROM view_accounts
                WITH READ ONLY;

                selectAll:
                SELECT account_id, account_status, account_created_at
                FROM account_status_view;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create sequence statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE SEQUENCE IF NOT EXISTS account_id_seq
                  START WITH 1
                  INCREMENT BY 1
                  MINVALUE 1
                  NOMAXVALUE
                  CACHE 20
                  NOCYCLE
                  ORDER
                  KEEP
                  SCALE EXTEND
                  NOSHARD
                  GLOBAL;

                CREATE SEQUENCE session_event_seq
                  START WITH 100
                  INCREMENT BY 10
                  MAXVALUE 1000000
                  NOMINVALUE
                  NOCACHE
                  CYCLE
                  NOORDER
                  NOKEEP
                  NOSCALE
                  SHARD NOEXTEND
                  SESSION;

                CREATE SEQUENCE hr.employee_seq
                  START WITH 500
                  NOCACHE;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle drop sequence statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP SEQUENCE IF EXISTS account_id_seq;

                DROP SEQUENCE hr.employee_seq;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle alter sequence statements through SQLDelight environment exactly") {
            val sql =
                """
                ALTER SEQUENCE IF EXISTS account_id_seq
                  RESTART
                  START WITH 42
                  INCREMENT BY 2
                  MAXVALUE 10000
                  MINVALUE 1
                  CACHE 10
                  NOCYCLE
                  NOORDER
                  NOKEEP
                  SCALE NOEXTEND
                  SHARD EXTEND
                  GLOBAL;

                ALTER SEQUENCE hr.employee_seq
                  NOMAXVALUE
                  NOMINVALUE
                  NOCACHE
                  CYCLE
                  ORDER
                  KEEP
                  NOSCALE
                  NOSHARD
                  SESSION;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle merge statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE account_balance (
                  account_id NUMBER PRIMARY KEY,
                  balance NUMBER,
                  updated_at TIMESTAMP
                );

                CREATE TABLE account_delta (
                  account_id NUMBER PRIMARY KEY,
                  delta NUMBER
                );

                CREATE TABLE merge_error_log (
                  message VARCHAR2(100)
                );

                CREATE TABLE audit_target (
                  id NUMBER PRIMARY KEY,
                  payload VARCHAR2(100)
                );

                CREATE TABLE audit_source (
                  id NUMBER PRIMARY KEY,
                  payload VARCHAR2(100)
                );

                MERGE INTO account_balance target
                USING (
                  SELECT account_id, delta
                  FROM account_delta
                ) source
                ON (1 = 1)
                WHEN MATCHED THEN UPDATE SET
                  balance = 100,
                  updated_at = CURRENT_TIMESTAMP
                  WHERE 1 <> 0
                  DELETE WHERE 0 = 1
                WHEN NOT MATCHED THEN INSERT (account_id, balance, updated_at)
                  VALUES (1, DEFAULT, CURRENT_TIMESTAMP)
                  WHERE 1 <> 0
                LOG ERRORS INTO merge_error_log ('account-balance') REJECT LIMIT UNLIMITED;

                MERGE INTO audit_target
                USING audit_source source
                ON (1 = 0)
                WHEN NOT MATCHED THEN INSERT
                  SET id = 1,
                      payload = DEFAULT;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle call statements through SQLDelight environment exactly") {
            val sql =
                """
                CALL remove_dept(162);

                CALL emp_mgmt.remove_dept(162);

                CALL hr.employee_api.adjust_salary(100, 2500, CURRENT_TIMESTAMP);

                CALL refresh_cache();
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle lock table statements through SQLDelight environment exactly") {
            val sql =
                """
                LOCK TABLE employees IN EXCLUSIVE MODE NOWAIT;

                LOCK TABLE hr.employees, hr.departments IN SHARE MODE;

                LOCK TABLE sales PARTITION (sales_q1) IN ROW SHARE MODE WAIT 30;

                LOCK TABLE sales PARTITION FOR (2026, 1), sales SUBPARTITION (sales_q1_north)
                IN SHARE ROW EXCLUSIVE MODE;

                LOCK TABLE sales SUBPARTITION FOR ('NORTH') IN SHARE UPDATE MODE;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle explain plan statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE explain_employees (
                  id NUMBER PRIMARY KEY,
                  department_id NUMBER,
                  salary NUMBER
                );

                CREATE TABLE explain_departments (
                  id NUMBER PRIMARY KEY
                );

                EXPLAIN PLAN
                  SET STATEMENT_ID = 'employee lookup'
                  INTO plan_table
                  FOR SELECT id, salary
                      FROM explain_employees
                      WHERE department_id = 10;

                EXPLAIN PLAN FOR
                  UPDATE explain_employees
                  SET salary = salary + 100
                  WHERE department_id = 10;

                EXPLAIN PLAN FOR
                  DELETE FROM explain_employees
                  WHERE department_id = 20;

                EXPLAIN PLAN FOR
                  MERGE INTO explain_employees target
                  USING explain_departments source
                  ON (1 = 1)
                  WHEN MATCHED THEN UPDATE SET salary = 100;

                EXPLAIN PLAN FOR
                  CREATE TABLE explain_snapshot AS
                  SELECT id, salary
                  FROM explain_employees;

                EXPLAIN PLAN FOR
                  CREATE INDEX explain_employees_department_idx
                  ON explain_employees (department_id);
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle truncate table statements through SQLDelight environment exactly") {
            val sql =
                """
                TRUNCATE TABLE employees_demo;

                TRUNCATE TABLE hr.sales_demo PRESERVE MATERIALIZED VIEW LOG DROP STORAGE;

                TRUNCATE TABLE orders_demo PURGE SNAPSHOT LOG DROP ALL STORAGE CASCADE;

                TRUNCATE TABLE private_temp_orders REUSE STORAGE;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle truncate cluster statements through SQLDelight environment exactly") {
            val sql =
                """
                TRUNCATE CLUSTER personnel;

                TRUNCATE CLUSTER hr.personnel DROP STORAGE;

                TRUNCATE CLUSTER archived_personnel REUSE STORAGE;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle materialized drop statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP MATERIALIZED VIEW LOG ON customers;

                DROP MATERIALIZED VIEW LOG IF EXISTS ON oe.customers;

                DROP SNAPSHOT LOG ON legacy_customers;

                DROP MATERIALIZED ZONEMAP sales_zmap;

                DROP MATERIALIZED ZONEMAP IF EXISTS reporting.sales_zmap;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle drop synonym statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP SYNONYM customers_synonym;

                DROP SYNONYM IF EXISTS oe.customers_synonym;

                DROP PUBLIC SYNONYM customers;

                DROP PUBLIC SYNONYM IF EXISTS customer_type_synonym FORCE;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle drop trigger statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP TRIGGER salary_check;

                DROP TRIGGER IF EXISTS hr.salary_check;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle drop type statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP TYPE person_t;

                DROP TYPE IF EXISTS hr.person_t FORCE;

                DROP TYPE employee_subtype VALIDATE;

                DROP TYPE BODY data_typ1;

                DROP TYPE BODY IF EXISTS hr.data_typ1;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle PL/SQL and Java drop statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP FUNCTION oe.SecondMax;

                DROP FUNCTION IF EXISTS reporting.calculate_bonus;

                DROP PROCEDURE hr.remove_emp;

                DROP PROCEDURE IF EXISTS archive.purge_history;

                DROP PACKAGE emp_mgmt;

                DROP PACKAGE BODY IF EXISTS hr.emp_mgmt;

                DROP LIBRARY ext_lib;

                DROP LIBRARY IF EXISTS hr.ext_lib;

                DROP JAVA SOURCE IF EXISTS AgentSource;

                DROP JAVA CLASS Agent;

                DROP JAVA RESOURCE IF EXISTS hr.config_properties;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle analytic drop statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP ANALYTIC VIEW sales_av;

                DROP ANALYTIC VIEW IF EXISTS sh.sales_av;

                DROP ATTRIBUTE DIMENSION product_attr_dim;

                DROP ATTRIBUTE DIMENSION IF EXISTS sh.product_attr_dim;

                DROP HIERARCHY product_hier;

                DROP HIERARCHY IF EXISTS sh.product_hier;

                DROP DIMENSION customers_dim;

                DROP DIMENSION sh.customers_dim;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle schema object drop statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP CLUSTER language;

                DROP CLUSTER IF EXISTS hr.personnel INCLUDING TABLES CASCADE CONSTRAINTS;

                DROP PUBLIC DATABASE LINK remote;

                DROP DATABASE LINK IF EXISTS ralph.linktosales;

                DROP DIRECTORY IF EXISTS bfile_dir;

                DROP INDEXTYPE IF EXISTS hr.position_indextype FORCE;

                DROP OPERATOR eq_op;

                DROP OPERATOR IF EXISTS hr.eq_op FORCE;

                DROP OUTLINE salaries;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle graph, Iceberg, context, and MLE drop statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP PROPERTY GRAPH IF EXISTS hr.customer_graph;

                DROP PROPERTY GRAPH sales_graph;

                DROP ICEBERG TABLE lake.sales_orders WITHIN CATALOG lake_catalog PURGE;

                DROP ICEBERG TABLE sales_orders_archive WITHIN CATALOG archive_catalog;

                DROP CONTEXT hr_context;

                DROP MLE ENV IF EXISTS hr.analytics_env;

                DROP MLE ENV scratch_env;

                DROP MLE MODULE IF EXISTS hr.forecast_module;

                DROP MLE MODULE cleanup_module;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("reports malformed Oracle SQL through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE sample (
                  id NUMBER(10),
                  name VARCHAR2(100)
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors =
                        listOf(
                            "Test.sq: (1, 19): '(', '.', ';' or AS expected, got '('",
                        ),
                )
        }
    })

private data class ParseResult(
    val fileNames: List<String>,
    val errors: List<String>,
)

private fun parseOracleSql(
    sql: String,
    fileName: String = "Test.sq",
): ParseResult {
    val root = Files.createTempDirectory("sqldelight-oracle-parser-test").toFile()
    val sourceDirectory = File(root, "com/example").apply { mkdirs() }
    File(sourceDirectory, fileName).writeText(sql)

    val errors = mutableListOf<String>()
    val compilationUnit = OracleParserTestCompilationUnit(File(root, "output"))
    val environment =
        SqlDelightEnvironment(
            sourceFolders = listOf(root),
            dependencyFolders = emptyList(),
            properties = OracleParserTestDatabaseProperties(root, compilationUnit),
            dialect = OracleDialect(),
            verifyMigrations = true,
            moduleName = "oracle-parser-test",
            compilationUnit = compilationUnit,
        )

    LanguageParserDefinitions.INSTANCE.forLanguage(SqlDelightLanguage).createParser(environment.project)
    LanguageParserDefinitions.INSTANCE.forLanguage(MigrationLanguage).createParser(environment.project)
    environment.annotate(listOf(OptimisticLockCompilerAnnotator()), createAnnotationHolder(errors))

    val fileNames = mutableListOf<String>()
    environment.forSourceFiles { psiFile ->
        if (psiFile is SqlDelightQueriesFile) {
            fileNames += psiFile.name
        }
    }

    return ParseResult(
        fileNames = fileNames.sorted(),
        errors = errors,
    )
}

private data class OracleParserTestCompilationUnit(
    override val outputDirectoryFile: File,
) : SqlDelightCompilationUnit {
    override val name: String = "test"
    override val sourceFolders: Set<SqlDelightSourceFolder> = emptySet()
}

private data class OracleParserTestDatabaseProperties(
    override val rootDirectory: File,
    private val compilationUnit: SqlDelightCompilationUnit,
) : SqlDelightDatabaseProperties {
    override val packageName: String = "com.example"
    override val className: String = "TestDatabase"
    override val dependencies: List<SqlDelightDatabaseName> = emptyList()
    override val compilationUnits: List<SqlDelightCompilationUnit> = listOf(compilationUnit)
    override val deriveSchemaFromMigrations: Boolean = false
    override val generateAsync: Boolean = false
    override val expandSelectStar: Boolean = true
    override val treatNullAsUnknownForEquality: Boolean = false
}

private fun createAnnotationHolder(errors: MutableList<String>): SqlAnnotationHolder =
    SqlAnnotationHolder { element, message ->
        val documentManager = PsiDocumentManager.getInstance(element.project)
        val document = requireNotNull(documentManager.getDocument(element.containingFile))
        val lineNumber = document.getLineNumber(element.textOffset)
        val offsetInLine = element.textOffset - document.getLineStartOffset(lineNumber)
        errors += "${element.containingFile.name}: (${lineNumber + 1}, $offsetInLine): $message"
    }
