package dev.s7a.sqldelight.oracle.dialects.oracle

import app.cash.sqldelight.core.SqlDelightCompilationUnit
import app.cash.sqldelight.core.SqlDelightDatabaseName
import app.cash.sqldelight.core.SqlDelightDatabaseProperties
import app.cash.sqldelight.core.SqlDelightEnvironment
import app.cash.sqldelight.core.SqlDelightSourceFolder
import app.cash.sqldelight.core.annotators.OptimisticLockCompilerAnnotator
import app.cash.sqldelight.core.lang.MigrationLanguage
import app.cash.sqldelight.core.lang.SqlDelightLanguage
import app.cash.sqldelight.core.lang.SqlDelightQueriesFile
import com.alecstrong.sql.psi.core.SqlAnnotationHolder
import com.intellij.lang.LanguageParserDefinitions
import com.intellij.psi.PsiDocumentManager
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import java.io.File
import java.nio.file.Files

class OracleParserBackedTest :
    FunSpec({
        test("parses Oracle create table type names through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE sample (
                  id NUMBER(10) NOT NULL,
                  amount NUMBER(10, 2),
                  name NATIONAL CHARACTER VARYING(100),
                  payload JSON,
                  raw_uuid RAW(16),
                  embedding VECTOR(3, FLOAT32),
                  created_at TIMESTAMP(6) WITH LOCAL TIME ZONE,
                  elapsed INTERVAL DAY TO SECOND
                );

                selectAll:
                SELECT id, amount, name, payload, raw_uuid, embedding, created_at, elapsed
                FROM sample;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle inline column constraints through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE accounts (
                  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                  external_id VARCHAR2(64) CONSTRAINT accounts_external_id_unique UNIQUE ENABLE NOVALIDATE,
                  status VARCHAR2(16) DEFAULT 'ACTIVE' NOT NULL,
                  archived_at TIMESTAMP INVISIBLE,
                  parent_id NUMBER REFERENCES accounts(id) DEFERRABLE INITIALLY DEFERRED
                );

                selectAll:
                SELECT id, external_id, status, archived_at, parent_id
                FROM accounts;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle table constraints through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE account_events (
                  account_id NUMBER NOT NULL,
                  event_id NUMBER NOT NULL,
                  parent_event_id NUMBER,
                  event_type VARCHAR2(64) NOT NULL,
                  event_payload JSON,
                  CONSTRAINT account_events_pk PRIMARY KEY (account_id, event_id) ENABLE,
                  CONSTRAINT account_events_type_unique UNIQUE (account_id, event_type) DEFERRABLE INITIALLY IMMEDIATE,
                  CONSTRAINT account_events_payload_check CHECK (event_payload IS NOT NULL) NOVALIDATE,
                  CONSTRAINT account_events_parent_fk FOREIGN KEY (account_id, parent_event_id) REFERENCES account_events(account_id, event_id) DEFERRABLE INITIALLY DEFERRED
                );

                selectAll:
                SELECT account_id, event_id, parent_event_id, event_type, event_payload
                FROM account_events;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create table statement variants through SQLDelight environment exactly") {
            val sql =
                """
                CREATE GLOBAL TEMPORARY TABLE IF NOT EXISTS staged_accounts (
                  account_id NUMBER NOT NULL,
                  external_id VARCHAR2(64),
                  CONSTRAINT staged_accounts_pk PRIMARY KEY (account_id)
                ) ON COMMIT PRESERVE ROWS;

                CREATE PRIVATE TEMPORARY TABLE private_staged_accounts (
                  account_id NUMBER NOT NULL,
                  external_id VARCHAR2(64)
                ) ON COMMIT DELETE ROWS;

                CREATE TABLE account_snapshot AS
                SELECT account_id, external_id
                FROM staged_accounts;

                selectAll:
                SELECT account_id, external_id
                FROM account_snapshot;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle alter table statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE alter_targets (
                  id NUMBER PRIMARY KEY,
                  status VARCHAR2(16)
                );

                ALTER TABLE alter_targets ADD created_at TIMESTAMP;
                ALTER TABLE alter_targets ADD (
                  updated_at TIMESTAMP,
                  archived_at TIMESTAMP INVISIBLE
                );
                ALTER TABLE alter_targets ADD CONSTRAINT alter_targets_status_check CHECK (status IS NOT NULL) ENABLE;
                ALTER TABLE alter_targets MODIFY (
                  created_at TIMESTAMP NOT NULL,
                  updated_at TIMESTAMP NOT NULL
                );
                ALTER TABLE alter_targets MODIFY status VARCHAR2(32) NOT NULL;
                ALTER TABLE alter_targets RENAME COLUMN status TO account_status;
                ALTER TABLE alter_targets DROP COLUMN archived_at CASCADE CONSTRAINTS;
                ALTER TABLE alter_targets DROP COLUMN created_at CASCADE CONSTRAINTS;
                ALTER TABLE alter_targets DROP CONSTRAINT alter_targets_status_check;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create index statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE indexed_accounts (
                  id NUMBER PRIMARY KEY,
                  status VARCHAR2(32) NOT NULL,
                  created_at TIMESTAMP,
                  archived_at TIMESTAMP
                );

                CREATE UNIQUE INDEX IF NOT EXISTS indexed_accounts_status_idx
                ON indexed_accounts (status) VISIBLE ONLINE;

                CREATE BITMAP INDEX indexed_accounts_archive_idx
                ON indexed_accounts (archived_at, created_at) INVISIBLE NOLOGGING;

                CREATE INDEX indexed_accounts_created_idx
                ON indexed_accounts (created_at DESC) REVERSE COMPUTE STATISTICS;

                CREATE INDEX indexed_accounts_status_upper_idx
                ON indexed_accounts (UPPER(status));

                selectAll:
                SELECT id, status, created_at, archived_at
                FROM indexed_accounts;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create view statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE view_accounts (
                  id NUMBER PRIMARY KEY,
                  status VARCHAR2(32) NOT NULL,
                  created_at TIMESTAMP
                );

                CREATE OR REPLACE FORCE EDITIONING VIEW account_status_view AS
                SELECT id AS account_id, status AS account_status, created_at AS account_created_at
                FROM view_accounts
                WHERE status IS NOT NULL
                BEQUEATH CURRENT_USER
                WITH CHECK OPTION;

                CREATE NO FORCE VIEW readonly_account_view AS
                SELECT id, status
                FROM view_accounts
                WITH READ ONLY;

                selectAll:
                SELECT account_id, account_status, account_created_at
                FROM account_status_view;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create sequence statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE SEQUENCE IF NOT EXISTS account_id_seq
                  START WITH 1
                  INCREMENT BY 1
                  MINVALUE 1
                  NOMAXVALUE
                  CACHE 20
                  NOCYCLE
                  ORDER
                  KEEP
                  SCALE EXTEND
                  NOSHARD
                  GLOBAL;

                CREATE SEQUENCE session_event_seq
                  START WITH 100
                  INCREMENT BY 10
                  MAXVALUE 1000000
                  NOMINVALUE
                  NOCACHE
                  CYCLE
                  NOORDER
                  NOKEEP
                  NOSCALE
                  SHARD NOEXTEND
                  SESSION;

                CREATE SEQUENCE hr.employee_seq
                  START WITH 500
                  NOCACHE;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle drop sequence statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP SEQUENCE IF EXISTS account_id_seq;

                DROP SEQUENCE hr.employee_seq;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle alter sequence statements through SQLDelight environment exactly") {
            val sql =
                """
                ALTER SEQUENCE IF EXISTS account_id_seq
                  RESTART
                  START WITH 42
                  INCREMENT BY 2
                  MAXVALUE 10000
                  MINVALUE 1
                  CACHE 10
                  NOCYCLE
                  NOORDER
                  NOKEEP
                  SCALE NOEXTEND
                  SHARD EXTEND
                  GLOBAL;

                ALTER SEQUENCE hr.employee_seq
                  NOMAXVALUE
                  NOMINVALUE
                  NOCACHE
                  CYCLE
                  ORDER
                  KEEP
                  NOSCALE
                  NOSHARD
                  SESSION;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle merge statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE account_balance (
                  account_id NUMBER PRIMARY KEY,
                  balance NUMBER,
                  updated_at TIMESTAMP
                );

                CREATE TABLE account_delta (
                  account_id NUMBER PRIMARY KEY,
                  delta NUMBER
                );

                CREATE TABLE merge_error_log (
                  message VARCHAR2(100)
                );

                CREATE TABLE audit_target (
                  id NUMBER PRIMARY KEY,
                  payload VARCHAR2(100)
                );

                CREATE TABLE audit_source (
                  id NUMBER PRIMARY KEY,
                  payload VARCHAR2(100)
                );

                MERGE INTO account_balance target
                USING (
                  SELECT account_id, delta
                  FROM account_delta
                ) source
                ON (1 = 1)
                WHEN MATCHED THEN UPDATE SET
                  balance = 100,
                  updated_at = CURRENT_TIMESTAMP
                  WHERE 1 <> 0
                  DELETE WHERE 0 = 1
                WHEN NOT MATCHED THEN INSERT (account_id, balance, updated_at)
                  VALUES (1, DEFAULT, CURRENT_TIMESTAMP)
                  WHERE 1 <> 0
                LOG ERRORS INTO merge_error_log ('account-balance') REJECT LIMIT UNLIMITED;

                MERGE INTO audit_target
                USING audit_source source
                ON (1 = 0)
                WHEN NOT MATCHED THEN INSERT
                  SET id = 1,
                      payload = DEFAULT;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle call statements through SQLDelight environment exactly") {
            val sql =
                """
                CALL remove_dept(162);

                CALL emp_mgmt.remove_dept(162);

                CALL hr.employee_api.adjust_salary(100, 2500, CURRENT_TIMESTAMP);

                CALL refresh_cache();
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle lock table statements through SQLDelight environment exactly") {
            val sql =
                """
                LOCK TABLE employees IN EXCLUSIVE MODE NOWAIT;

                LOCK TABLE hr.employees, hr.departments IN SHARE MODE;

                LOCK TABLE sales PARTITION (sales_q1) IN ROW SHARE MODE WAIT 30;

                LOCK TABLE sales PARTITION FOR (2026, 1), sales SUBPARTITION (sales_q1_north)
                IN SHARE ROW EXCLUSIVE MODE;

                LOCK TABLE sales SUBPARTITION FOR ('NORTH') IN SHARE UPDATE MODE;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle explain plan statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE explain_employees (
                  id NUMBER PRIMARY KEY,
                  department_id NUMBER,
                  salary NUMBER
                );

                CREATE TABLE explain_departments (
                  id NUMBER PRIMARY KEY
                );

                EXPLAIN PLAN
                  SET STATEMENT_ID = 'employee lookup'
                  INTO plan_table
                  FOR SELECT id, salary
                      FROM explain_employees
                      WHERE department_id = 10;

                EXPLAIN PLAN FOR
                  UPDATE explain_employees
                  SET salary = salary + 100
                  WHERE department_id = 10;

                EXPLAIN PLAN FOR
                  DELETE FROM explain_employees
                  WHERE department_id = 20;

                EXPLAIN PLAN FOR
                  MERGE INTO explain_employees target
                  USING explain_departments source
                  ON (1 = 1)
                  WHEN MATCHED THEN UPDATE SET salary = 100;

                EXPLAIN PLAN FOR
                  CREATE TABLE explain_snapshot AS
                  SELECT id, salary
                  FROM explain_employees;

                EXPLAIN PLAN FOR
                  CREATE INDEX explain_employees_department_idx
                  ON explain_employees (department_id);
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle truncate table statements through SQLDelight environment exactly") {
            val sql =
                """
                TRUNCATE TABLE employees_demo;

                TRUNCATE TABLE hr.sales_demo PRESERVE MATERIALIZED VIEW LOG DROP STORAGE;

                TRUNCATE TABLE orders_demo PURGE SNAPSHOT LOG DROP ALL STORAGE CASCADE;

                TRUNCATE TABLE private_temp_orders REUSE STORAGE;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle truncate cluster statements through SQLDelight environment exactly") {
            val sql =
                """
                TRUNCATE CLUSTER personnel;

                TRUNCATE CLUSTER hr.personnel DROP STORAGE;

                TRUNCATE CLUSTER archived_personnel REUSE STORAGE;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle materialized drop statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP MATERIALIZED VIEW LOG ON customers;

                DROP MATERIALIZED VIEW LOG IF EXISTS ON oe.customers;

                DROP SNAPSHOT LOG ON legacy_customers;

                DROP MATERIALIZED ZONEMAP sales_zmap;

                DROP MATERIALIZED ZONEMAP IF EXISTS reporting.sales_zmap;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle drop synonym statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP SYNONYM customers_synonym;

                DROP SYNONYM IF EXISTS oe.customers_synonym;

                DROP PUBLIC SYNONYM customers;

                DROP PUBLIC SYNONYM IF EXISTS customer_type_synonym FORCE;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle materialized log and zonemap alter statements exactly") {
            val sql =
                """
                ALTER MATERIALIZED VIEW LOG ON order_items ADD ROWID;

                ALTER MATERIALIZED VIEW LOG IF EXISTS ON hr.employees
                  ADD (commission_pct)
                  EXCLUDING NEW VALUES;

                ALTER SNAPSHOT LOG ON legacy_customers INCLUDING NEW VALUES;

                ALTER MATERIALIZED VIEW LOG ON sales
                  PURGE IMMEDIATE ASYNCHRONOUS;

                ALTER MATERIALIZED VIEW LOG ON sales
                  FOR SYNCHRONOUS REFRESH;

                ALTER MATERIALIZED VIEW LOG ON sales
                  PCTFREE 20 PCTUSED 50 NOCACHE PARALLEL 4;

                ALTER MATERIALIZED ZONEMAP sales_zmap
                  PCTFREE 20 PCTUSED 50 NOCACHE;

                ALTER MATERIALIZED ZONEMAP IF EXISTS reporting.sales_zmap
                  REFRESH FAST ON DEMAND ENABLE PRUNING;

                ALTER MATERIALIZED ZONEMAP sales_zmap COMPILE;

                ALTER MATERIALIZED ZONEMAP sales_zmap REBUILD;

                ALTER MATERIALIZED ZONEMAP sales_zmap UNUSABLE;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle drop trigger statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP TRIGGER salary_check;

                DROP TRIGGER IF EXISTS hr.salary_check;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle PL/SQL create boundary statements exactly") {
            val sql =
                """
                CREATE OR REPLACE EDITIONABLE FUNCTION hr.second_max
                  RETURN NUMBER
                  AS LANGUAGE JAVA
                  NAME 'SecondMax.evaluate(int) return int';

                CREATE NONEDITIONABLE FUNCTION IF NOT EXISTS reporting.calculate_bonus
                  RETURN NUMBER
                  AS LANGUAGE JAVASCRIPT
                  NAME 'bonus.calculate';

                CREATE OR REPLACE PACKAGE BODY emp_mgmt
                  AS END emp_mgmt;

                CREATE TYPE BODY IF NOT EXISTS data_typ1
                  AS END data_typ1;

                CREATE OR REPLACE LIBRARY ext_lib
                  AS '/u01/app/oracle/lib/ext_lib.so';
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle alter PL/SQL and Java statements exactly") {
            val sql =
                """
                ALTER FUNCTION IF EXISTS hr.second_max COMPILE DEBUG REUSE SETTINGS;

                ALTER FUNCTION reporting.calculate_bonus NONEDITIONABLE;

                ALTER PROCEDURE hr.remove_emp COMPILE;

                ALTER PACKAGE emp_mgmt COMPILE BODY REUSE SETTINGS;

                ALTER LIBRARY ext_lib COMPILE;

                ALTER JAVA SOURCE IF EXISTS AgentSource COMPILE AUTHID CURRENT_USER;

                ALTER JAVA CLASS Agent RESOLVE AUTHID DEFINER;

                ALTER SYNONYM offices COMPILE;

                ALTER PUBLIC SYNONYM emp_table COMPILE;

                ALTER TRIGGER IF EXISTS hr.salary_check DISABLE;

                ALTER TRIGGER salary_check RENAME TO salary_check_new;

                ALTER TYPE IF EXISTS data_typ1 COMPILE BODY REUSE SETTINGS;

                ALTER TYPE person_t FINAL;

                ALTER TYPE address_t ADD ATTRIBUTE postal_code VARCHAR2;

                ALTER TYPE address_t CASCADE INCLUDING TABLE DATA;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle drop type statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP TYPE person_t;

                DROP TYPE IF EXISTS hr.person_t FORCE;

                DROP TYPE employee_subtype VALIDATE;

                DROP TYPE BODY data_typ1;

                DROP TYPE BODY IF EXISTS hr.data_typ1;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle PL/SQL and Java drop statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP FUNCTION oe.SecondMax;

                DROP FUNCTION IF EXISTS reporting.calculate_bonus;

                DROP PROCEDURE hr.remove_emp;

                DROP PROCEDURE IF EXISTS archive.purge_history;

                DROP PACKAGE emp_mgmt;

                DROP PACKAGE BODY IF EXISTS hr.emp_mgmt;

                DROP LIBRARY ext_lib;

                DROP LIBRARY IF EXISTS hr.ext_lib;

                DROP JAVA SOURCE IF EXISTS AgentSource;

                DROP JAVA CLASS Agent;

                DROP JAVA RESOURCE IF EXISTS hr.config_properties;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle analytic drop statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP ANALYTIC VIEW sales_av;

                DROP ANALYTIC VIEW IF EXISTS sh.sales_av;

                DROP ATTRIBUTE DIMENSION product_attr_dim;

                DROP ATTRIBUTE DIMENSION IF EXISTS sh.product_attr_dim;

                DROP HIERARCHY product_hier;

                DROP HIERARCHY IF EXISTS sh.product_hier;

                DROP DIMENSION customers_dim;

                DROP DIMENSION sh.customers_dim;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle analytic dimension alter statements through SQLDelight environment exactly") {
            val sql =
                """
                ALTER ANALYTIC VIEW sales_av RENAME TO mysales_av;

                ALTER ANALYTIC VIEW IF EXISTS sh.sales_av COMPILE;

                ALTER ANALYTIC VIEW sales_av
                  ADD CACHE MEASURE GROUP (sales, units, cost)
                  LEVELS (time.fiscal.fiscal_quarter, warehouse);

                ALTER ANALYTIC VIEW sales_av
                  DROP CACHE MEASURE GROUP (sales)
                  LEVELS (time.fiscal.fiscal_quarter);

                ALTER ATTRIBUTE DIMENSION product_attr_dim RENAME TO my_product_attr_dim;

                ALTER ATTRIBUTE DIMENSION IF EXISTS sh.product_attr_dim COMPILE;

                ALTER HIERARCHY product_hier RENAME TO myproduct_hier;

                ALTER HIERARCHY IF EXISTS sh.product_hier COMPILE;

                ALTER DIMENSION customers_dim DROP ATTRIBUTE country;

                ALTER DIMENSION sh.customers_dim
                  ADD LEVEL zone IS customers.cust_postal_code
                  ADD ATTRIBUTE zone DETERMINES (cust_city);

                ALTER DIMENSION customers_dim COMPILE;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle schema object drop statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP CLUSTER language;

                DROP CLUSTER IF EXISTS hr.personnel INCLUDING TABLES CASCADE CONSTRAINTS;

                DROP PUBLIC DATABASE LINK remote;

                DROP DATABASE LINK IF EXISTS ralph.linktosales;

                DROP DIRECTORY IF EXISTS bfile_dir;

                DROP INDEXTYPE IF EXISTS hr.position_indextype FORCE;

                DROP OPERATOR eq_op;

                DROP OPERATOR IF EXISTS hr.eq_op FORCE;

                DROP OUTLINE salaries;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle schema object alter statements through SQLDelight environment exactly") {
            val sql =
                """
                ALTER CLUSTER personnel SIZE 1024 CACHE;

                ALTER CLUSTER IF EXISTS hr.language DEALLOCATE UNUSED KEEP 30 K;

                ALTER DATABASE LINK private_link
                  CONNECT TO hr IDENTIFIED BY hr_new_password;

                ALTER PUBLIC DATABASE LINK public_link
                  CONNECT TO scott IDENTIFIED BY scott_new_password;

                ALTER SHARED PUBLIC DATABASE LINK shared_pub_link
                  CONNECT TO scott IDENTIFIED BY scott_new_password
                  AUTHENTICATED BY hr IDENTIFIED BY hr_new_password;

                ALTER DATABASE LINK IF EXISTS private_credential_link
                  CONNECT WITH hr_credential;

                ALTER INDEXTYPE position_indextype COMPILE;

                ALTER INDEXTYPE IF EXISTS hr.position_indextype
                  ADD OPERATOR eq_op(NUMBER, NUMBER);

                ALTER OPERATOR eq_op COMPILE;

                ALTER OPERATOR IF EXISTS hr.eq_op
                  DROP BINDING (NUMBER, NUMBER) FORCE;

                ALTER OUTLINE salaries REBUILD;

                ALTER PRIVATE OUTLINE session_outline RENAME TO session_outline_v2;

                ALTER PUBLIC OUTLINE salaries CHANGE CATEGORY TO reporting;

                ALTER OUTLINE salaries DISABLE;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle graph, Iceberg, context, and MLE drop statements through SQLDelight environment exactly") {
            val sql =
                """
                DROP PROPERTY GRAPH IF EXISTS hr.customer_graph;

                DROP PROPERTY GRAPH sales_graph;

                DROP ICEBERG TABLE lake.sales_orders WITHIN CATALOG lake_catalog PURGE;

                DROP ICEBERG TABLE sales_orders_archive WITHIN CATALOG archive_catalog;

                DROP CONTEXT hr_context;

                DROP MLE ENV IF EXISTS hr.analytics_env;

                DROP MLE ENV scratch_env;

                DROP MLE MODULE IF EXISTS hr.forecast_module;

                DROP MLE MODULE cleanup_module;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle graph and JSON duality view alter statements through SQLDelight environment exactly") {
            val sql =
                """
                ALTER PROPERTY GRAPH g COMPILE;

                ALTER PROPERTY GRAPH IF EXISTS hr.customer_graph COMPILE;

                ALTER JSON DUALITY VIEW orders_dv ENABLE LOGICAL REPLICATION;

                ALTER JSON RELATIONAL DUALITY VIEW IF EXISTS hr.orders_dv DISABLE LOGICAL REPLICATION;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle MLE alter statements through SQLDelight environment exactly") {
            val sql =
                """
                ALTER MLE ENV scott.myenv
                  ADD IMPORTS ("math" MODULE scott.math_module);

                ALTER MLE ENV IF EXISTS scott.myenv
                  ALTER IMPORTS ("util" MODULE scott.util_module, "config" MODULE scott.config_module);

                ALTER MLE ENV scott.myenv
                  DROP IMPORTS ("math", "util");

                ALTER MLE ENV scott.myenv
                  SET LANGUAGE OPTIONS 'js.strict=true';

                ALTER MLE ENV scott.myenv COMPILE;

                ALTER MLE MODULE IF EXISTS scott.my_mle_module
                  SET METADATA USING CLOB (
                    SELECT JSON('{ "version": "1.2.0" }')
                  );
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle assertion, directive, edition, flashback, and In-Memory drop statements exactly") {
            val sql =
                """
                DROP ASSERTION IF EXISTS company_must_have_a_president;

                DROP ASSERTION hr.salary_within_job_limit;

                DROP DIRECTIVE validate_email_directive;

                DROP EDITION old_release IF EXISTS CASCADE;

                DROP EDITION patch_release;

                DROP FLASHBACK ARCHIVE archive_a;

                DROP INMEMORY JOIN GROUP IF EXISTS sh.prod_id1;

                DROP INMEMORY JOIN GROUP prod_id2;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle administrative legacy drop statements exactly") {
            val sql =
                """
                DROP LOCKDOWN PROFILE hr_prof;

                DROP PMEM FILESTORE cloud_db_1 EXCLUDING CONTENTS;

                DROP PMEM FILESTORE cloud_db_2 INCLUDING CONTENTS;

                DROP PMEM FILESTORE cloud_db_3 FORCE INCLUDING CONTENTS;

                DROP PROFILE app_user CASCADE;

                DROP PROFILE reporting_user;

                DROP ROLLBACK SEGMENT rbs_one;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle administrative drop statements exactly") {
            val sql =
                """
                DROP DATABASE;

                DROP PLUGGABLE DATABASE pdb1 INCLUDING DATAFILES;

                DROP PLUGGABLE DATABASE app_root_clone FORCE KEEP DATAFILES;

                DROP TABLESPACE IF EXISTS tbs_01 DROP QUOTA INCLUDING CONTENTS CASCADE CONSTRAINTS;

                DROP TABLESPACE tbs_02 INCLUDING CONTENTS AND DATAFILES;

                DROP TABLESPACE SET ts1 KEEP QUOTA INCLUDING CONTENTS KEEP DATAFILES;

                DROP DISKGROUP dgroup_01 INCLUDING CONTENTS;

                DROP DISKGROUP dgroup_02 FORCE INCLUDING CONTENTS;

                DROP RESTORE POINT good_data;

                DROP RESTORE POINT pdb_good_data FOR PLUGGABLE DATABASE pdb1;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle transaction constraint statements exactly") {
            val sql =
                """
                COMMIT;

                COMMIT WORK;

                COMMIT COMMENT 'monthly close';

                COMMIT WORK WRITE NOWAIT BATCH;

                COMMIT FORCE '22.57.53', 1;

                SAVEPOINT before_batch;

                ROLLBACK;

                ROLLBACK WORK TO before_batch;

                ROLLBACK TO SAVEPOINT before_batch;

                ROLLBACK FORCE '25.32.87';

                SET TRANSACTION READ ONLY;

                SET TRANSACTION READ WRITE NAME 'bulk load';

                SET TRANSACTION ISOLATION LEVEL SERIALIZABLE NAME 'serial report';

                SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

                SET TRANSACTION USE ROLLBACK SEGMENT rbs_one;

                SET TRANSACTION NAME 'named transaction';

                SET CONSTRAINTS ALL IMMEDIATE;

                SET CONSTRAINT emp_job_nn DEFERRED;

                SET CONSTRAINTS emp_job_nn, emp_salary_min, hr.jhist_dept_fk DEFERRED;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle role and data grant session statements exactly") {
            val sql =
                """
                SET ROLE dw_manager IDENTIFIED BY warehouse_password;

                SET ROLE app_user, reporting_user IDENTIFIED BY reporting_password;

                SET ROLE ALL;

                SET ROLE ALL EXCEPT dw_manager, app_admin;

                SET ROLE NONE;

                SET USE DATA GRANTS ONLY ON hr.employees ENABLED;

                SET USE DATA GRANTS ONLY ON employees_view DISABLED;

                SET USE DATA GRANTS ONLY ON reporting.sales_summary;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle alter session and alter system statements exactly") {
            val sql =
                """
                ALTER SESSION ADVISE COMMIT;

                ALTER SESSION CLOSE DATABASE LINK local;

                ALTER SESSION ENABLE PARALLEL DML;

                ALTER SESSION FORCE PARALLEL QUERY PARALLEL 8;

                ALTER SESSION ENABLE RESUMABLE TIMEOUT 3600 NAME 'bulk load';

                ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY MM DD HH24:MI:SS';

                ALTER SESSION SET CONTAINER = pdb1 SERVICE = app_service;

                ALTER SESSION SET ROW ARCHIVAL VISIBILITY = ALL;

                ALTER SYSTEM ARCHIVE LOG CHANGE 9356083;

                ALTER SYSTEM CHECKPOINT;

                ALTER SYSTEM FLUSH SHARED_POOL;

                ALTER SYSTEM SWITCH LOGFILE;

                ALTER SYSTEM ENABLE RESTRICTED SESSION;

                ALTER SYSTEM DISABLE DISTRIBUTED RECOVERY;

                ALTER SYSTEM KILL SESSION '39, 23' IMMEDIATE;

                ALTER SYSTEM DISCONNECT SESSION '13, 8' POST_TRANSACTION;

                ALTER SYSTEM SET QUERY_REWRITE_ENABLED = TRUE;

                ALTER SYSTEM SET DISPATCHERS = '(INDEX=0)(PROTOCOL=TCP)(DISPATCHERS=5)', '(INDEX=1)(PROTOCOL=ipc)(DISPATCHERS=10)';

                ALTER SYSTEM SET RESOURCE_LIMIT = TRUE SCOPE = BOTH SID = '*';

                ALTER SYSTEM RESET resource_limit SCOPE = SPFILE SID = '*';
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle administer key management statements exactly") {
            val sql =
                """
                ADMINISTER KEY MANAGEMENT
                  CREATE KEYSTORE '/etc/ORACLE/WALLETS/orcl'
                  IDENTIFIED BY password;

                ADMINISTER KEY MANAGEMENT
                  CREATE AUTO_LOGIN KEYSTORE FROM KEYSTORE '/etc/ORACLE/WALLETS/orcl'
                  IDENTIFIED BY password;

                ADMINISTER KEY MANAGEMENT
                  SET KEYSTORE OPEN
                  IDENTIFIED BY password
                  CONTAINER = CURRENT;

                ADMINISTER KEY MANAGEMENT
                  SET KEYSTORE CLOSE;

                ADMINISTER KEY MANAGEMENT
                  SET KEYSTORE OPEN
                  IDENTIFIED BY EXTERNAL STORE;

                ADMINISTER KEY MANAGEMENT
                  BACKUP KEYSTORE USING 'hr.emp_keystore'
                  IDENTIFIED BY password
                  TO '/etc/ORACLE/KEYSTORE/DB1/';

                ADMINISTER KEY MANAGEMENT
                  ALTER KEYSTORE PASSWORD IDENTIFIED BY old_password
                  SET new_password WITH BACKUP USING 'pwd_change';

                ADMINISTER KEY MANAGEMENT
                  MERGE KEYSTORE '/etc/ORACLE/KEYSTORE/DB1'
                  AND KEYSTORE '/etc/ORACLE/KEYSTORE/DB2'
                  IDENTIFIED BY existing_keystore_password
                  INTO NEW KEYSTORE '/etc/ORACLE/KEYSTORE/DB3'
                  IDENTIFIED BY new_keystore_password;

                ADMINISTER KEY MANAGEMENT
                  MERGE KEYSTORE '/etc/ORACLE/KEYSTORE/DB1'
                  INTO EXISTING KEYSTORE '/etc/ORACLE/KEYSTORE/DB2'
                  IDENTIFIED BY existing_keystore_password
                  WITH BACKUP;

                ADMINISTER KEY MANAGEMENT
                  ISOLATE KEYSTORE IDENTIFIED BY isolated_keystore_password
                  FROM ROOT KEYSTORE FORCE KEYSTORE
                  IDENTIFIED BY united_keystore_password
                  WITH BACKUP USING 'isolate_backup';

                ADMINISTER KEY MANAGEMENT
                  UNITE KEYSTORE IDENTIFIED BY isolated_keystore_password
                  WITH ROOT KEYSTORE
                  IDENTIFIED BY EXTERNAL STORE
                  WITH BACKUP USING 'unite_backup';

                ADMINISTER KEY MANAGEMENT
                  SET KEY USING ALGORITHM 'AES256'
                  IDENTIFIED BY password
                  WITH BACKUP;

                ADMINISTER KEY MANAGEMENT
                  SET ENCRYPTION KEY 'mkid:mk' USING TAG 'rotation-2026' USING ALGORITHM 'AES256'
                  FORCE KEYSTORE
                  IDENTIFIED BY EXTERNAL STORE
                  WITH BACKUP
                  CONTAINER = ALL;

                ADMINISTER KEY MANAGEMENT
                  CREATE KEY USING TAG 'mykey1'
                  IDENTIFIED BY password
                  WITH BACKUP;

                ADMINISTER KEY MANAGEMENT
                  USE KEY 'ARgEtzPxpE'
                  IDENTIFIED BY password
                  WITH BACKUP;

                ADMINISTER KEY MANAGEMENT
                  SET TAG 'mykey2' FOR 'ARgEtzPxpE'
                  FORCE KEYSTORE
                  IDENTIFIED BY password
                  WITH BACKUP;

                ADMINISTER KEY MANAGEMENT
                  EXPORT KEYS WITH SECRET 'my_secret'
                  TO '/etc/TDE/export.exp'
                  IDENTIFIED BY password
                  WITH IDENTIFIER IN 'AdoxnJ0uH08', 'AW5z3CoyKE';

                ADMINISTER KEY MANAGEMENT
                  IMPORT KEYS WITH SECRET 'my_secret'
                  FROM '/etc/TDE/export.exp'
                  IDENTIFIED BY password
                  WITH BACKUP;

                ADMINISTER KEY MANAGEMENT
                  SET ENCRYPTION KEY IDENTIFIED BY user_password
                  MIGRATE USING software_keystore_password
                  WITH BACKUP;

                ADMINISTER KEY MANAGEMENT
                  SET ENCRYPTION KEY IDENTIFIED BY software_keystore_password
                  REVERSE MIGRATE USING user_password;

                ADMINISTER KEY MANAGEMENT
                  ADD SECRET 'secret1' FOR CLIENT 'client1'
                  USING TAG 'My first secret'
                  IDENTIFIED BY password
                  WITH BACKUP;

                ADMINISTER KEY MANAGEMENT
                  UPDATE SECRET 'secret1' FOR CLIENT 'client1'
                  USING TAG 'New Tag 1'
                  IDENTIFIED BY password
                  WITH BACKUP;

                ADMINISTER KEY MANAGEMENT
                  DELETE SECRET FOR CLIENT 'client1'
                  IDENTIFIED BY password
                  WITH BACKUP;

                ADMINISTER KEY MANAGEMENT
                  SWITCHOVER TO LIBRARY 'updated_pkcs11.so' FOR ALL CONTAINERS;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle unified audit statements exactly") {
            val sql =
                """
                CREATE AUDIT POLICY table_pol
                  PRIVILEGES CREATE ANY TABLE, DROP ANY TABLE;

                CREATE AUDIT POLICY dml_pol
                  ACTIONS DELETE ON hr.employees,
                          INSERT ON hr.employees,
                          UPDATE ON hr.employees,
                          ALL ON hr.departments;

                CREATE AUDIT POLICY read_dir_pol
                  ACTIONS READ ON DIRECTORY bfile_dir;

                CREATE AUDIT POLICY security_pol
                  ACTIONS ADMINISTER KEY MANAGEMENT;

                CREATE AUDIT POLICY dp_actions_pol
                  ACTIONS COMPONENT = datapump IMPORT;

                CREATE AUDIT POLICY java_pol
                  ROLES java_admin, java_deploy;

                CREATE AUDIT POLICY order_updates_pol
                  ACTIONS UPDATE ON oe.orders
                  WHEN 'SYS_CONTEXT(''USERENV'', ''IDENTIFICATION_TYPE'') = ''EXTERNAL'''
                  EVALUATE PER SESSION;

                CREATE AUDIT POLICY local_table_pol
                  PRIVILEGES CREATE ANY TABLE, DROP ANY TABLE
                  CONTAINER = CURRENT;

                CREATE AUDIT POLICY c##common_role1_pol
                  ROLES c##role1
                  CONTAINER = ALL;

                CREATE AUDIT POLICY column_pol
                  ACTIONS GRANT(job) ON scott.emp;

                ALTER AUDIT POLICY dml_pol
                  ADD PRIVILEGES CREATE ANY TABLE, DROP ANY TABLE;

                ALTER AUDIT POLICY security_pol
                  ADD PRIVILEGES CREATE ANY LIBRARY, DROP ANY LIBRARY
                      ACTIONS DELETE ON hr.employees,
                              INSERT ON hr.employees,
                              UPDATE ON hr.employees,
                              ALL ON hr.departments
                      ROLES dba, connect;

                ALTER AUDIT POLICY dml_pol
                  DROP ACTIONS INSERT ON hr.employees,
                               UPDATE ON hr.employees;

                ALTER AUDIT POLICY dp_actions_pol
                  ADD ACTIONS COMPONENT = datapump EXPORT
                  DROP ACTIONS COMPONENT = datapump IMPORT;

                ALTER AUDIT POLICY order_updates_pol
                  CONDITION DROP;

                ALTER AUDIT POLICY emp_updates_pol
                  CONDITION WHEN 'UID = 102'
                  EVALUATE PER STATEMENT;

                ALTER AUDIT POLICY hr_audit_policy ADD ONLY TOPLEVEL;

                ALTER AUDIT POLICY hr_audit_policy DROP ONLY TOPLEVEL;

                AUDIT POLICY table_pol;

                AUDIT POLICY dml_pol BY hr, sh;

                AUDIT POLICY read_dir_pol EXCEPT hr;

                AUDIT POLICY security_pol BY hr WHENEVER NOT SUCCESSFUL;

                AUDIT POLICY common_role1_pol BY USERS WITH GRANTED ROLES c##role1;

                AUDIT CONTEXT NAMESPACE userenv
                  ATTRIBUTES current_user, db_name
                  BY hr;

                NOAUDIT POLICY table_pol;

                NOAUDIT POLICY dml_pol BY hr, sh;

                NOAUDIT POLICY common_role1_pol BY USERS WITH GRANTED ROLES c##role1;

                NOAUDIT CONTEXT NAMESPACE userenv
                  ATTRIBUTES current_user, db_name
                  BY hr WHENEVER NOT SUCCESSFUL;

                DROP AUDIT POLICY table_pol;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle role and user security statements exactly") {
            val sql =
                """
                CREATE USER IF NOT EXISTS app_user IDENTIFIED BY app_password
                  DEFAULT COLLATION binary_ci
                  DEFAULT TABLESPACE users
                  TEMPORARY TABLESPACE temp
                  QUOTA 100 M ON users
                  PROFILE app_profile
                  PASSWORD EXPIRE
                  ACCOUNT UNLOCK
                  ENABLE EDITIONS FORCE
                  CONTAINER = CURRENT
                  READ WRITE;

                CREATE USER external_user IDENTIFIED EXTERNALLY AS 'CN=External User'
                  ACCOUNT LOCK;

                CREATE USER global_user IDENTIFIED GLOBALLY AS 'IAM_GROUP_NAME = analytics'
                  QUOTA UNLIMITED ON data;

                CREATE USER no_auth_user NO AUTHENTICATION DEFAULT TABLESPACE users;

                ALTER USER IF EXISTS app_user IDENTIFIED BY new_password REPLACE app_password
                  DEFAULT ROLE app_reader, app_writer
                  PASSWORD EXPIRE
                  ACCOUNT LOCK;

                ALTER USER app_user ADD ( FACTOR 'otp' AS 'external-otp' );

                ALTER USER app_user UPDATE ( FACTOR 'otp' AS 'external-otp-v2' );

                ALTER USER app_user DROP FACTOR 'otp';

                ALTER USER app_user DEFAULT ROLE ALL EXCEPT app_admin;

                ALTER USER app_user EXPIRE PASSWORD ROLLOVER PERIOD;

                ALTER USER app_user ENABLE DICTIONARY PROTECTION READ ONLY;

                ALTER USER app_user SET CONTAINER_DATA = ALL;

                ALTER USER app_user SET CONTAINER_DATA = DEFAULT FOR sys.cdb_users;

                ALTER USER app_user ADD CONTAINER_DATA = (pdb1, pdb2) FOR sys.cdb_tables;

                ALTER USER app_user REMOVE CONTAINER_DATA = (pdb3);

                ALTER USER app_user GRANT CONNECT THROUGH sh WITH ROLE warehouse_user AUTHENTICATION REQUIRED;

                ALTER USER app_user GRANT CONNECT THROUGH app_proxy WITH NO ROLES;

                ALTER USER app_user GRANT CONNECT THROUGH ENTERPRISE USERS;

                ALTER USER app_user REVOKE CONNECT THROUGH sh;

                ALTER USER app_user, reporting_user REVOKE CONNECT THROUGH ENTERPRISE USERS;

                CREATE ROLE IF NOT EXISTS app_reader NOT IDENTIFIED;

                CREATE ROLE app_writer IDENTIFIED BY writer_password CONTAINER = CURRENT;

                CREATE ROLE app_external IDENTIFIED EXTERNALLY CONTAINER = ALL;

                CREATE ROLE app_global IDENTIFIED GLOBALLY AS 'IAM_GROUP_NAME = analytics';

                CREATE ROLE app_package IDENTIFIED USING security.role_auth;

                ALTER ROLE IF EXISTS app_reader IDENTIFIED BY reader_password;

                ALTER ROLE app_writer NOT IDENTIFIED CONTAINER = ALL;

                ALTER ROLE app_external IDENTIFIED GLOBALLY AS 'AZURE_ROLE = app-role';

                GRANT CREATE SESSION, CREATE TABLE TO app_user WITH ADMIN OPTION;

                GRANT SELECT ANY TABLE TO app_reader CONTAINER = CURRENT;

                GRANT app_runtime TO app_user IDENTIFIED BY runtime_password;

                GRANT SELECT, INSERT, UPDATE (name, status) ON hr.employees TO app_user WITH GRANT OPTION;

                GRANT app_role TO PROCEDURE hr.run_job;

                REVOKE CREATE SESSION FROM app_user;

                REVOKE SELECT ANY TABLE FROM app_reader CONTAINER = ALL;

                REVOKE SELECT, UPDATE ON hr.employees FROM app_user CASCADE CONSTRAINTS;

                REVOKE app_role FROM PROCEDURE hr.run_job;

                DROP ROLE IF EXISTS app_reader;

                DROP ROLE app_writer;

                DROP USER IF EXISTS old_app_user CASCADE;

                DROP USER staging_user;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle analyze statements exactly") {
            val sql =
                """
                ANALYZE TABLE hr.employees VALIDATE STRUCTURE CASCADE;

                ANALYZE TABLE customers VALIDATE REF UPDATE SET DANGLING TO NULL;

                ANALYZE INDEX hr.employee_name_idx PARTITION (sales_q1)
                  VALIDATE STRUCTURE CASCADE COMPLETE ONLINE INTO invalid_rows;

                ANALYZE CLUSTER personnel LIST CHAINED ROWS INTO chained_rows;

                ANALYZE TABLE orders DELETE SYSTEM STATISTICS;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle associate and disassociate statistics statements exactly") {
            val sql =
                """
                ASSOCIATE STATISTICS WITH COLUMNS hr.employees.salary, hr.employees.commission_pct
                  USING salary_stats WITH SYSTEM MANAGED STORAGE TABLES;

                ASSOCIATE STATISTICS WITH FUNCTIONS hr.compensation_cost USING cost_stats;

                ASSOCIATE STATISTICS WITH PACKAGES hr.estimates USING NULL;

                ASSOCIATE STATISTICS WITH TYPES hr.employee_t
                  DEFAULT COST (1, 2, 3), DEFAULT SELECTIVITY 10;

                ASSOCIATE STATISTICS WITH INDEXTYPES hr.position_indextype
                  DEFAULT SELECTIVITY 5, DEFAULT COST (10, 20, 30)
                  WITH USER MANAGED STORAGE TABLES;

                DISASSOCIATE STATISTICS FROM COLUMNS hr.employees.salary, hr.employees.commission_pct FORCE;

                DISASSOCIATE STATISTICS FROM FUNCTIONS hr.compensation_cost;

                DISASSOCIATE STATISTICS FROM INDEXTYPES hr.position_indextype FORCE;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle rename and comment statements exactly") {
            val sql =
                """
                RENAME departments_new TO emp_departments;

                COMMENT ON AUDIT POLICY policy_user_actions IS 'Unified audit policy comment';

                COMMENT ON COLUMN employees.job_id IS 'abbreviated job title';

                COMMENT ON COLUMN hr.employees.salary IS '';

                COMMENT ON EDITION patch_release IS 'Patch release edition';

                COMMENT ON INDEXTYPE hr.position_indextype IS 'Position indextype';

                COMMENT ON MATERIALIZED VIEW reporting.sales_mv IS 'Sales materialized view';

                COMMENT ON MINING MODEL sh.sales_model IS 'Sales mining model';

                COMMENT ON OPERATOR hr.eq_op IS 'Equality operator';

                COMMENT ON TABLE employees IS 'Employee table';

                COMMENT ON TABLE hr.employee_view IS 'Employee view';

                COMMENT ON PROPERTY GRAPH hr.customer_graph IS 'Customer graph';
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle purge and flashback statements exactly") {
            val sql =
                """
                PURGE TABLE employees;

                PURGE INDEX hr.employee_name_idx;

                PURGE TABLESPACE users USER hr;

                PURGE TABLESPACE SET shard_ts USER app_user;

                PURGE RECYCLEBIN;

                PURGE DBA_RECYCLEBIN;

                FLASHBACK TABLE hr.employees, hr.departments TO SCN 123456 ENABLE TRIGGERS;

                FLASHBACK TABLE employees TO TIMESTAMP CURRENT_TIMESTAMP DISABLE TRIGGERS;

                FLASHBACK TABLE old_employees TO RESTORE POINT before_cleanup;

                FLASHBACK TABLE dropped_employees TO BEFORE DROP RENAME TO employees;

                FLASHBACK DATABASE TO RESTORE POINT before_upgrade;

                FLASHBACK STANDBY PLUGGABLE DATABASE pdb1 TO BEFORE RESETLOGS;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("reports malformed Oracle SQL through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE sample (
                  id NUMBER(10),
                  name VARCHAR2(100)
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors =
                        listOf(
                            "Test.sq: (1, 19): '(', '.', ';' or AS expected, got '('",
                        ),
                )
        }
    })

private data class ParseResult(
    val fileNames: List<String>,
    val errors: List<String>,
)

private fun parseOracleSql(
    sql: String,
    fileName: String = "Test.sq",
): ParseResult {
    val root = Files.createTempDirectory("sqldelight-oracle-parser-test").toFile()
    val sourceDirectory = File(root, "com/example").apply { mkdirs() }
    File(sourceDirectory, fileName).writeText(sql)

    val errors = mutableListOf<String>()
    val compilationUnit = OracleParserTestCompilationUnit(File(root, "output"))
    val environment =
        SqlDelightEnvironment(
            sourceFolders = listOf(root),
            dependencyFolders = emptyList(),
            properties = OracleParserTestDatabaseProperties(root, compilationUnit),
            dialect = OracleDialect(),
            verifyMigrations = true,
            moduleName = "oracle-parser-test",
            compilationUnit = compilationUnit,
        )

    LanguageParserDefinitions.INSTANCE.forLanguage(SqlDelightLanguage).createParser(environment.project)
    LanguageParserDefinitions.INSTANCE.forLanguage(MigrationLanguage).createParser(environment.project)
    environment.annotate(listOf(OptimisticLockCompilerAnnotator()), createAnnotationHolder(errors))

    val fileNames = mutableListOf<String>()
    environment.forSourceFiles { psiFile ->
        if (psiFile is SqlDelightQueriesFile) {
            fileNames += psiFile.name
        }
    }

    return ParseResult(
        fileNames = fileNames.sorted(),
        errors = errors,
    )
}

private data class OracleParserTestCompilationUnit(
    override val outputDirectoryFile: File,
) : SqlDelightCompilationUnit {
    override val name: String = "test"
    override val sourceFolders: Set<SqlDelightSourceFolder> = emptySet()
}

private data class OracleParserTestDatabaseProperties(
    override val rootDirectory: File,
    private val compilationUnit: SqlDelightCompilationUnit,
) : SqlDelightDatabaseProperties {
    override val packageName: String = "com.example"
    override val className: String = "TestDatabase"
    override val dependencies: List<SqlDelightDatabaseName> = emptyList()
    override val compilationUnits: List<SqlDelightCompilationUnit> = listOf(compilationUnit)
    override val deriveSchemaFromMigrations: Boolean = false
    override val generateAsync: Boolean = false
    override val expandSelectStar: Boolean = true
    override val treatNullAsUnknownForEquality: Boolean = false
}

private fun createAnnotationHolder(errors: MutableList<String>): SqlAnnotationHolder =
    SqlAnnotationHolder { element, message ->
        val documentManager = PsiDocumentManager.getInstance(element.project)
        val document = requireNotNull(documentManager.getDocument(element.containingFile))
        val lineNumber = document.getLineNumber(element.textOffset)
        val offsetInLine = element.textOffset - document.getLineStartOffset(lineNumber)
        errors += "${element.containingFile.name}: (${lineNumber + 1}, $offsetInLine): $message"
    }
