package dev.s7a.sqldelight.oracle.dialect

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import org.testcontainers.containers.OracleContainer
import org.testcontainers.utility.DockerImageName
import java.math.BigDecimal
import java.sql.Connection
import java.sql.DriverManager

class OracleContainerSmokeTest :
    FunSpec({
        var oracle: OracleContainer? = null

        beforeSpec {
            if (oracleTestcontainersEnabled) {
                oracle =
                    OracleContainer(oracleTestcontainersDockerImageName).also { container ->
                        container.withSharedMemorySize(oracleTestcontainersSharedMemoryBytes)
                        container.start()
                    }
            }
        }

        afterSpec {
            oracle?.stop()
        }

        test("executes Oracle DDL and DML with Testcontainers when enabled") {
            if (!oracleTestcontainersEnabled) return@test

            oracle.requireStarted().connection().use { connection ->
                connection.createStatement().use { statement ->
                    statement.executeUpdate(
                        """
                        CREATE TABLE sqldelight_oracle_smoke (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR2(100) NOT NULL,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                        )
                        """.trimIndent(),
                    )
                    statement.executeUpdate("INSERT INTO sqldelight_oracle_smoke (name) VALUES ('alpha')") shouldBe 1
                }

                connection
                    .prepareStatement("SELECT name FROM sqldelight_oracle_smoke WHERE id = ?")
                    .use { statement ->
                        statement.setLong(1, 1L)
                        statement.executeQuery().use { resultSet ->
                            resultSet.next() shouldBe true
                            resultSet.getString(1) shouldBe "alpha"
                            resultSet.next() shouldBe false
                        }
                    }
            }
        }

        test("round-trips representative Oracle type names with Testcontainers when enabled") {
            if (!oracleTestcontainersEnabled) return@test

            oracle.requireStarted().connection().use { connection ->
                connection.createStatement().use { statement ->
                    statement.executeUpdate(
                        """
                        CREATE TABLE sqldelight_oracle_types (
                            id NUMBER(19) PRIMARY KEY,
                            code CHAR(3 CHAR) NOT NULL,
                            label VARCHAR2(100 CHAR) NOT NULL,
                            amount NUMBER(10, 2) NOT NULL,
                            ratio BINARY_DOUBLE NOT NULL,
                            created_on DATE NOT NULL,
                            changed_at TIMESTAMP NOT NULL,
                            raw_value RAW(16) NOT NULL,
                            note CLOB NOT NULL
                        )
                        """.trimIndent(),
                    )
                }

                connection
                    .prepareStatement(
                        """
                        INSERT INTO sqldelight_oracle_types (
                            id,
                            code,
                            label,
                            amount,
                            ratio,
                            created_on,
                            changed_at,
                            raw_value,
                            note
                        )
                        VALUES (
                            ?,
                            ?,
                            ?,
                            ?,
                            ?,
                            DATE '2026-06-21',
                            TIMESTAMP '2026-06-21 12:34:56',
                            HEXTORAW('00112233445566778899AABBCCDDEEFF'),
                            ?
                        )
                        """.trimIndent(),
                    ).use { statement ->
                        statement.setLong(1, 1001L)
                        statement.setString(2, "ABC")
                        statement.setString(3, "alpha")
                        statement.setBigDecimal(4, BigDecimal("1234.56"))
                        statement.setDouble(5, 0.125)
                        statement.setString(6, "large text")
                        statement.executeUpdate() shouldBe 1
                    }

                connection
                    .prepareStatement(
                        """
                        SELECT
                            id,
                            code,
                            label,
                            amount,
                            ratio,
                            TO_CHAR(created_on, 'YYYY-MM-DD'),
                            TO_CHAR(changed_at, 'YYYY-MM-DD HH24:MI:SS'),
                            RAWTOHEX(raw_value),
                            note
                        FROM sqldelight_oracle_types
                        """.trimIndent(),
                    ).use { statement ->
                        statement.executeQuery().use { resultSet ->
                            resultSet.next() shouldBe true
                            resultSet.getLong(1) shouldBe 1001L
                            resultSet.getString(2) shouldBe "ABC"
                            resultSet.getString(3) shouldBe "alpha"
                            resultSet.getBigDecimal(4) shouldBe BigDecimal("1234.56")
                            resultSet.getDouble(5) shouldBe 0.125
                            resultSet.getString(6) shouldBe "2026-06-21"
                            resultSet.getString(7) shouldBe "2026-06-21 12:34:56"
                            resultSet.getString(8) shouldBe "00112233445566778899AABBCCDDEEFF"
                            resultSet.getString(9) shouldBe "large text"
                            resultSet.next() shouldBe false
                        }
                    }
            }
        }

        test("round-trips Oracle INSERT UPDATE MERGE and DELETE with Testcontainers when enabled") {
            if (!oracleTestcontainersEnabled) return@test

            oracle.requireStarted().connection().use { connection ->
                connection.createStatement().use { statement ->
                    statement.executeUpdate(
                        """
                        CREATE TABLE sqldelight_oracle_dml (
                            id NUMBER(19) PRIMARY KEY,
                            label VARCHAR2(100) NOT NULL,
                            revision NUMBER(10) NOT NULL
                        )
                        """.trimIndent(),
                    )
                    statement.executeUpdate("INSERT INTO sqldelight_oracle_dml (id, label, revision) VALUES (1, 'alpha', 1)") shouldBe 1
                    statement.executeUpdate("UPDATE sqldelight_oracle_dml SET label = 'beta', revision = 2 WHERE id = 1") shouldBe 1
                    statement.executeUpdate(
                        """
                        MERGE INTO sqldelight_oracle_dml target
                        USING (SELECT 1 AS id, 'gamma' AS label, 3 AS revision FROM dual) source
                        ON (target.id = source.id)
                        WHEN MATCHED THEN
                            UPDATE SET target.label = source.label, target.revision = source.revision
                        WHEN NOT MATCHED THEN
                            INSERT (id, label, revision) VALUES (source.id, source.label, source.revision)
                        """.trimIndent(),
                    ) shouldBe 1
                }

                connection
                    .prepareStatement("SELECT label, revision FROM sqldelight_oracle_dml WHERE id = ?")
                    .use { statement ->
                        statement.setLong(1, 1L)
                        statement.executeQuery().use { resultSet ->
                            resultSet.next() shouldBe true
                            resultSet.getString(1) shouldBe "gamma"
                            resultSet.getInt(2) shouldBe 3
                            resultSet.next() shouldBe false
                        }
                    }

                connection.createStatement().use { statement ->
                    statement.executeUpdate("DELETE FROM sqldelight_oracle_dml WHERE id = 1") shouldBe 1
                }

                connection.prepareStatement("SELECT COUNT(*) FROM sqldelight_oracle_dml").use { statement ->
                    statement.executeQuery().use { resultSet ->
                        resultSet.next() shouldBe true
                        resultSet.getInt(1) shouldBe 0
                        resultSet.next() shouldBe false
                    }
                }
            }
        }
    })

private val oracleTestcontainersEnabled: Boolean =
    System.getenv("ORACLE_TESTCONTAINERS") == "true"

private val oracleTestcontainersImage: String =
    System.getenv("ORACLE_TESTCONTAINERS_IMAGE") ?: "gvenzl/oracle-xe:21-slim-faststart"

private val oracleTestcontainersSharedMemoryBytes: Long =
    System.getenv("ORACLE_TESTCONTAINERS_SHM_BYTES")?.toLongOrNull() ?: 2L * 1024L * 1024L * 1024L

private val oracleTestcontainersServiceName: String? =
    System.getenv("ORACLE_TESTCONTAINERS_SERVICE_NAME")?.takeIf { value -> value.isNotBlank() }

private val oracleTestcontainersDockerImageName: DockerImageName =
    DockerImageName
        .parse(oracleTestcontainersImage)
        .asCompatibleSubstituteFor("gvenzl/oracle-xe")

private fun OracleContainer?.requireStarted(): OracleContainer = requireNotNull(this)

private fun OracleContainer.connection(): Connection = DriverManager.getConnection(testJdbcUrl(), username, password)

private fun OracleContainer.testJdbcUrl(): String =
    oracleTestcontainersServiceName?.let { serviceName ->
        "jdbc:oracle:thin:@$host:$oraclePort/$serviceName"
    } ?: jdbcUrl
