package dev.s7a.sqldelight.oracle.dialect

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import org.testcontainers.containers.OracleContainer
import org.testcontainers.utility.DockerImageName
import java.sql.DriverManager

class OracleContainerSmokeTest :
    FunSpec({
        test("executes Oracle DDL and DML with Testcontainers when enabled") {
            if (!oracleTestcontainersEnabled) return@test

            OracleContainer(DockerImageName.parse(oracleTestcontainersImage)).use { oracle ->
                oracle.start()

                DriverManager.getConnection(oracle.jdbcUrl, oracle.username, oracle.password).use { connection ->
                    connection.createStatement().use { statement ->
                        statement.executeUpdate(
                            """
                            CREATE TABLE sqldelight_oracle_smoke (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR2(100) NOT NULL,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                            )
                            """.trimIndent(),
                        )
                        statement.executeUpdate("INSERT INTO sqldelight_oracle_smoke (name) VALUES ('alpha')")
                    }

                    connection
                        .prepareStatement("SELECT name FROM sqldelight_oracle_smoke WHERE id = ?")
                        .use { statement ->
                            statement.setLong(1, 1L)
                            statement.executeQuery().use { resultSet ->
                                resultSet.next() shouldBe true
                                resultSet.getString(1) shouldBe "alpha"
                            }
                        }
                }
            }
        }
    })

private val oracleTestcontainersEnabled: Boolean =
    System.getenv("ORACLE_TESTCONTAINERS") == "true"

private val oracleTestcontainersImage: String =
    System.getenv("ORACLE_TESTCONTAINERS_IMAGE") ?: "gvenzl/oracle-xe:21-slim-faststart"
