{
  // Specify the parent parser.
  overrides="com.alecstrong.sql.psi.core.SqlParser"
  elementTypeClass = "com.alecstrong.sql.psi.core.SqlElementType"

  implements="com.alecstrong.sql.psi.core.psi.SqlCompositeElement"
  extends="com.alecstrong.sql.psi.core.psi.SqlCompositeElementImpl"
  psiClassPrefix = "Oracle"

  parserImports=[
    "static com.alecstrong.sql.psi.core.SqlParser.*"
    "static com.alecstrong.sql.psi.core.psi.SqlTypes.COMMA"
    "static com.alecstrong.sql.psi.core.psi.SqlTypes.DIGIT"
    "static com.alecstrong.sql.psi.core.psi.SqlTypes.LP"
    "static com.alecstrong.sql.psi.core.psi.SqlTypes.RP"
    "static com.alecstrong.sql.psi.core.SqlParserUtil.identifierExt"
    "static com.alecstrong.sql.psi.core.SqlParserUtil.signedNumberExt"
  ]
}

overrides ::= type_name | column_constraint | table_constraint | create_table_stmt | alter_table_stmt | alter_table_rules | create_index_stmt | create_view_stmt | extension_stmt

type_name ::= oracle_type_name | core_type_name {
  extends = "com.alecstrong.sql.psi.core.psi.impl.SqlTypeNameImpl"
  implements = "com.alecstrong.sql.psi.core.psi.SqlTypeName"
  override = true
}

oracle_type_name ::= (
  oracle_numeric_type |
  oracle_character_type |
  oracle_binary_type |
  oracle_datetime_type |
  oracle_interval_type |
  oracle_named_type
)

private core_type_name ::= <<identifierExt identifier_real>> [ LP <<signedNumberExt signed_number_real>> RP | LP <<signedNumberExt signed_number_real>> COMMA <<signedNumberExt signed_number_real>> RP ]

private oracle_numeric_type ::= (
  ( 'NUMBER' | 'NUMERIC' | 'DECIMAL' | 'DEC' ) [ oracle_type_parameters ] |
  ( 'INTEGER' | 'INT' | 'SMALLINT' | 'BINARY_INTEGER' | 'PLS_INTEGER' ) |
  'FLOAT' [ oracle_type_parameters ] |
  'REAL' |
  'DOUBLE' 'PRECISION' |
  'BINARY_FLOAT' |
  'BINARY_DOUBLE' |
  'BOOLEAN'
)

private oracle_character_type ::= (
  ( 'CHAR' | 'CHARACTER' | 'NCHAR' | 'VARCHAR' | 'VARCHAR2' | 'NVARCHAR2' ) [ oracle_type_parameters ] |
  ( 'CHAR' | 'CHARACTER' ) 'VARYING' [ oracle_type_parameters ] |
  'NATIONAL' ( 'CHAR' | 'CHARACTER' ) [ 'VARYING' ] [ oracle_type_parameters ] |
  ( 'CLOB' | 'NCLOB' | 'LONG' | 'ROWID' | 'UROWID' | 'JSON' | 'XMLTYPE' )
)

private oracle_binary_type ::= ( 'RAW' [ oracle_type_parameters ] | 'LONG' 'RAW' | 'BLOB' | 'BFILE' )

private oracle_datetime_type ::= (
  'DATE' |
  'TIMESTAMP' [ oracle_type_parameters ] [ 'WITH' [ 'LOCAL' ] 'TIME' 'ZONE' ]
)

private oracle_interval_type ::= (
  'INTERVAL' 'YEAR' [ oracle_type_parameters ] 'TO' 'MONTH' |
  'INTERVAL' 'DAY' [ oracle_type_parameters ] 'TO' 'SECOND' [ oracle_type_parameters ]
)

private oracle_named_type ::= (
  'SDO_GEOMETRY' |
  'SDO_TOPO_GEOMETRY' |
  'SDO_GEORASTER' |
  'VECTOR' [ oracle_type_parameters ] |
  'OBJECT' |
  'REF' |
  'ANYTYPE' |
  'ANYDATA' |
  'ANYDATASET' |
  'URITYPE' |
  'DBURITYPE' |
  'XDBURITYPE' |
  'HTTPURITYPE' |
  'NESTED' 'TABLE' |
  'VARRAY' [ oracle_type_parameters ] |
  'VARYING' 'ARRAY' [ oracle_type_parameters ]
)

private oracle_type_parameters ::= LP oracle_type_parameter_token (oracle_type_parameter_token) * RP

private oracle_type_parameter_token ::= <<identifierExt identifier_real>> | oracle_vector_format | DIGIT | {signed_number} | COMMA

private oracle_vector_format ::= 'FLOAT32' | 'FLOAT64' | 'INT8' | 'BINARY'

column_constraint ::= [ 'CONSTRAINT' {identifier} ] (
  'PRIMARY' 'KEY' oracle_constraint_state * |
  [ 'NOT' ] 'NULL' oracle_constraint_state * |
  'UNIQUE' oracle_constraint_state * |
  {check_constraint} oracle_constraint_state * |
  {default_constraint} |
  'COLLATE' {collation_name} |
  {foreign_key_clause} oracle_constraint_state * |
  oracle_identity_clause |
  oracle_visibility
) {
  extends = "com.alecstrong.sql.psi.core.psi.impl.SqlColumnConstraintImpl"
  implements = "com.alecstrong.sql.psi.core.psi.SqlColumnConstraint"
  override = true
}

private oracle_identity_clause ::= 'GENERATED' ( 'ALWAYS' | 'BY' 'DEFAULT' [ 'ON' 'NULL' ] ) 'AS' 'IDENTITY' [ oracle_parenthesized_clause ]

private oracle_constraint_state ::= (
  oracle_visibility |
  'ENABLE' |
  'DISABLE' |
  [ 'NOT' ] 'DEFERRABLE' |
  'INITIALLY' ( 'IMMEDIATE' | 'DEFERRED' ) |
  [ 'NOT' ] 'RELY' |
  'NORELY' |
  [ 'NO' ] 'VALIDATE' |
  'NOVALIDATE'
)

private oracle_visibility ::= 'VISIBLE' | 'INVISIBLE'

private oracle_parenthesized_clause ::= LP oracle_clause_token * RP

private oracle_clause_token ::= <<identifierExt identifier_real>> | DIGIT | {signed_number} | COMMA | LP | RP

table_constraint ::= [ 'CONSTRAINT' {identifier} ] (
  ( 'PRIMARY' 'KEY' | 'UNIQUE' ) [ {index_name} ] LP {indexed_column} ( COMMA {indexed_column} ) * RP oracle_constraint_state * |
  {check_constraint} oracle_constraint_state * |
  'FOREIGN' 'KEY' LP {column_name} ( COMMA {column_name} ) * RP {foreign_key_clause} oracle_constraint_state *
) {
  extends = "com.alecstrong.sql.psi.core.psi.impl.SqlTableConstraintImpl"
  implements = "com.alecstrong.sql.psi.core.psi.SqlTableConstraint"
  override = true
}

create_table_stmt ::= 'CREATE' [ oracle_table_scope ] 'TABLE' [ 'IF' 'NOT' 'EXISTS' ] [ {database_name} DOT ] {table_name} (
  LP {column_def} ( COMMA {column_def} ) * ( COMMA {table_constraint} ) * RP [ oracle_on_commit_clause ] |
  'AS' {compound_select_stmt}
) {
  extends = "com.alecstrong.sql.psi.core.psi.impl.SqlCreateTableStmtImpl"
  implements = "com.alecstrong.sql.psi.core.psi.SqlCreateTableStmt"
  elementTypeClass = "com.alecstrong.sql.psi.core.psi.mixins.CreateTableElementType"
  stubClass = "com.alecstrong.sql.psi.core.psi.SchemaContributorStub"
  override = true
  pin = 6
}

private oracle_table_scope ::= ( 'GLOBAL' | 'PRIVATE' ) 'TEMPORARY' | 'TEMP' | 'TEMPORARY'

private oracle_on_commit_clause ::= 'ON' 'COMMIT' ( 'DELETE' | 'PRESERVE' ) 'ROWS'

alter_table_stmt ::= 'ALTER' 'TABLE' [ {database_name} DOT ] {table_name} {alter_table_rules} ( COMMA {alter_table_rules} ) * {
  extends = "com.alecstrong.sql.psi.core.psi.impl.SqlAlterTableStmtImpl"
  implements = "com.alecstrong.sql.psi.core.psi.SqlAlterTableStmt"
  elementTypeClass = "dev.s7a.sqldelight.oracle.dialects.oracle.grammar.mixins.AlterTableElementType"
  stubClass = "com.alecstrong.sql.psi.core.psi.mixins.AlterTableStmtStub"
  override = true
  pin = 1
}

alter_table_rules ::= (
  alter_table_add_columns |
  alter_table_add_constraint |
  alter_table_add_column |
  alter_table_modify_columns |
  alter_table_modify_column |
  alter_table_drop_constraint |
  alter_table_drop_column |
  alter_table_rename_column
) {
  extends = "com.alecstrong.sql.psi.core.psi.impl.SqlAlterTableRulesImpl"
  implements = "com.alecstrong.sql.psi.core.psi.SqlAlterTableRules"
  override = true
}

alter_table_add_column ::= 'ADD' [ 'COLUMN' ] {column_def} {
  extends = "com.alecstrong.sql.psi.core.psi.impl.SqlAlterTableAddColumnImpl"
  implements = "com.alecstrong.sql.psi.core.psi.SqlAlterTableAddColumn"
  override = true
  pin = 1
}

alter_table_add_columns ::= 'ADD' [ 'COLUMN' ] LP {column_def} ( COMMA {column_def} ) * RP {
  mixin = "dev.s7a.sqldelight.oracle.dialects.oracle.grammar.mixins.AlterTableAddColumnsMixin"
}

alter_table_add_constraint ::= 'ADD' {table_constraint} {
  mixin = "dev.s7a.sqldelight.oracle.dialects.oracle.grammar.mixins.AlterTableAddConstraintMixin"
}

alter_table_modify_columns ::= 'MODIFY' [ 'COLUMN' ] LP {column_def} ( COMMA {column_def} ) * RP {
  mixin = "dev.s7a.sqldelight.oracle.dialects.oracle.grammar.mixins.AlterTableModifyColumnsMixin"
}

alter_table_modify_column ::= 'MODIFY' [ 'COLUMN' ] {column_def} {
  mixin = "dev.s7a.sqldelight.oracle.dialects.oracle.grammar.mixins.AlterTableModifyColumnMixin"
  pin = 1
}

alter_table_drop_constraint ::= 'DROP' 'CONSTRAINT' {identifier} {
  pin = 2
}

alter_table_drop_column ::= 'DROP' [ 'COLUMN' ] {column_name} [ 'CASCADE' 'CONSTRAINTS' ] {
  mixin = "dev.s7a.sqldelight.oracle.dialects.oracle.grammar.mixins.AlterTableDropColumnMixin"
  pin = 1
}

alter_table_rename_column ::= 'RENAME' [ 'COLUMN' ] {column_name} 'TO' {column_alias} {
  mixin = "dev.s7a.sqldelight.oracle.dialects.oracle.grammar.mixins.AlterTableRenameColumnMixin"
  pin = 1
}

create_index_stmt ::= 'CREATE' [ oracle_index_kind ] 'INDEX' [ 'IF' 'NOT' 'EXISTS' ] [ {database_name} DOT ] {index_name} 'ON' {table_name}
  LP {indexed_column} ( COMMA {indexed_column} ) * RP oracle_index_attribute * {
  extends = "com.alecstrong.sql.psi.core.psi.impl.SqlCreateIndexStmtImpl"
  implements = "com.alecstrong.sql.psi.core.psi.SqlCreateIndexStmt"
  elementTypeClass = "com.alecstrong.sql.psi.core.psi.mixins.CreateIndexElementType"
  stubClass = "com.alecstrong.sql.psi.core.psi.SchemaContributorStub"
  override = true
  pin = 3
}

private oracle_index_kind ::= 'UNIQUE' | 'BITMAP'

private oracle_index_attribute ::= (
  oracle_visibility |
  'REVERSE' |
  'ONLINE' |
  'NOLOGGING' |
  'LOGGING' |
  'UNUSABLE' |
  'COMPUTE' 'STATISTICS' |
  'COMPRESS' [ {signed_number} ] |
  'NOCOMPRESS' |
  'INDEXING' ( 'FULL' | 'PARTIAL' )
)

create_view_stmt ::= 'CREATE' [ 'OR' 'REPLACE' ] [ 'FORCE' | 'NO' 'FORCE' ] [ 'EDITIONING' | 'EDITIONABLE' | 'NONEDITIONABLE' ] 'VIEW'
  [ {database_name} DOT ] {view_name} [ LP {column_alias} ( COMMA {column_alias} ) * RP ] 'AS' {compound_select_stmt}
  [ 'BEQUEATH' ( 'CURRENT_USER' | 'DEFINER' ) ] [ 'WITH' ( [ 'CASCADED' | 'LOCAL' ] 'CHECK' 'OPTION' | 'READ' 'ONLY' ) ] {
  extends = "com.alecstrong.sql.psi.core.psi.impl.SqlCreateViewStmtImpl"
  implements = "com.alecstrong.sql.psi.core.psi.TableElement"
  elementTypeClass = "com.alecstrong.sql.psi.core.psi.mixins.CreateViewElementType"
  stubClass = "com.alecstrong.sql.psi.core.psi.SchemaContributorStub"
  override = true
  pin = 6
}

extension_stmt ::= create_sequence_stmt {
  extends = "com.alecstrong.sql.psi.core.psi.impl.SqlExtensionStmtImpl"
  implements = "com.alecstrong.sql.psi.core.psi.SqlExtensionStmt"
  override = true
}

create_sequence_stmt ::= 'CREATE' 'SEQUENCE' [ 'IF' 'NOT' 'EXISTS' ] oracle_sequence_identifier oracle_sequence_clause * {
  pin = 2
}

private oracle_sequence_identifier ::= <<identifierExt <<identifier_real>>>> | string

private oracle_sequence_clause ::= (
  'INCREMENT' 'BY' {signed_number} |
  'START' 'WITH' {signed_number} |
  'MAXVALUE' {signed_number} |
  'NOMAXVALUE' |
  'MINVALUE' {signed_number} |
  'NOMINVALUE' |
  'CYCLE' |
  'NOCYCLE' |
  'CACHE' {signed_number} |
  'NOCACHE' |
  'ORDER' |
  'NOORDER' |
  'KEEP' |
  'NOKEEP' |
  'SCALE' [ 'EXTEND' | 'NOEXTEND' ] |
  'NOSCALE' |
  'SHARD' [ 'EXTEND' | 'NOEXTEND' ] |
  'NOSHARD' |
  'SESSION' |
  'GLOBAL'
)
