package dev.s7a.sqldelight.oracle.check.dialect

import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.AliasBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.ClauseBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.CommonFunctionName
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.DataTypeName
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.GroupByBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.JoinConditionBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.KeywordCaseTarget
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.OrderByBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.PredicateBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.SqlDelightExecutableStatementStart
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.SqlDelightStatementStart
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.StatementStart
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.TableReferenceBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.TransactionEndStatement
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.TransactionStartStatement
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatterns
import dev.s7a.sqldelight.check.api.sourcePatterns

/**
 * Conservative source scanner patterns for Oracle Database SQL.
 */
public val OracleDialectSourcePatterns: SqlDialectSourcePatterns =
    SqlDialectSourcePatterns(
        patterns =
            SqlDialectSourcePatterns.SourceScannerDefault.patterns +
                sourcePatterns(
                    "ALTER INDEX",
                    "ALTER DOMAIN",
                    "ALTER MATERIALIZED VIEW",
                    "ALTER ROLE",
                    "ALTER SEQUENCE",
                    "ALTER SESSION",
                    "ALTER SYSTEM",
                    "ALTER TABLE",
                    "ALTER USER",
                    "ALTER VIEW",
                    "ANALYZE",
                    "CALL",
                    "COMMENT",
                    "COMMIT",
                    "CREATE ANALYTIC VIEW",
                    "CREATE CLUSTER",
                    "CREATE DATABASE LINK",
                    "CREATE DIRECTORY",
                    "CREATE DOMAIN",
                    "CREATE FLEXIBLE DOMAIN",
                    "CREATE INDEXTYPE",
                    "CREATE MATERIALIZED VIEW",
                    "CREATE MATERIALIZED VIEW LOG",
                    "CREATE PACKAGE",
                    "CREATE PROCEDURE",
                    "CREATE PROPERTY GRAPH",
                    "CREATE ROLE",
                    "CREATE SEQUENCE",
                    "CREATE SYNONYM",
                    "CREATE TRIGGER",
                    "CREATE TYPE",
                    "CREATE USER",
                    "DROP INDEX",
                    "DROP DOMAIN",
                    "DROP MATERIALIZED VIEW",
                    "DROP ROLE",
                    "DROP SEQUENCE",
                    "DROP SYNONYM",
                    "DROP TABLE",
                    "DROP USER",
                    "DROP VIEW",
                    "EXPLAIN PLAN",
                    "FLASHBACK",
                    "GRANT",
                    "LOCK TABLE",
                    "MERGE",
                    "PURGE",
                    "RENAME",
                    "REVOKE",
                    "ROLLBACK",
                    "SAVEPOINT",
                    "SET CONSTRAINT",
                    "SET TRANSACTION",
                    "TRUNCATE",
                    roles = setOf(StatementStart, SqlDelightStatementStart),
                ) +
                sourcePatterns(
                    "INSERT ALL",
                    "INSERT FIRST",
                    "MERGE",
                    roles = setOf(SqlDelightExecutableStatementStart),
                ) +
                sourcePatterns("SET TRANSACTION", roles = setOf(TransactionStartStatement)) +
                sourcePatterns("COMMIT", "ROLLBACK", roles = setOf(TransactionEndStatement)) +
                sourcePatterns("CREATE SEQUENCE", roles = setOf(CreateSequenceStatementStart)) +
                sourcePatterns(
                    "AS OF SCN",
                    "AS OF TIMESTAMP",
                    "ADD MEASURES",
                    "ALTER DOMAIN",
                    "ANNOTATIONS",
                    "CHOOSE DOMAIN USING",
                    "CONNECT BY",
                    "COLUMNS",
                    "DEFAULT MEASURE",
                    "DEFAULT ON NULL",
                    "DESTINATION KEY",
                    "DISPLAY",
                    "DIMENSION BY",
                    "EDGE TABLES",
                    "ENUM",
                    "FETCH {FIRST|NEXT} [ROW|ROWS]",
                    "FILTER FACT",
                    "FOR UPDATE",
                    "GRAPH_TABLE",
                    "HIERARCHIES",
                    "INSERT ALL",
                    "INSERT FIRST",
                    "JSON_TABLE",
                    "MATCH",
                    "MATCH_RECOGNIZE",
                    "MEASURES",
                    "MODEL",
                    "OFFSET",
                    "ORDER",
                    "PIVOT",
                    "PROPERTIES",
                    "QUALIFY",
                    "RETURNING",
                    "SOURCE KEY",
                    "START WITH",
                    "STRICT",
                    "UNPIVOT",
                    "USECASE",
                    "VERTEX TABLES",
                    "VERSIONS BETWEEN",
                    "XMLTABLE",
                    roles = setOf(ClauseBoundary),
                ) +
                sourcePatterns("CONNECT BY", roles = setOf(ConnectByClause)) +
                sourcePatterns("START WITH", roles = setOf(StartWithClause)) +
                sourcePatterns("FETCH", "FOR", "OFFSET", "RETURNING", roles = setOf(OrderByBoundary)) +
                sourcePatterns(
                    "CONNECT",
                    "FETCH",
                    "FOR",
                    "GRAPH_TABLE",
                    "MATCH",
                    "MODEL",
                    "OFFSET",
                    "RETURNING",
                    "START",
                    roles = setOf(GroupByBoundary, PredicateBoundary, JoinConditionBoundary),
                ) +
                sourcePatterns("CONNECT", "FETCH", "FOR", "MODEL", "OFFSET", "START", roles = setOf(TableReferenceBoundary)) +
                sourcePatterns(
                    "ANYDATA",
                    "BFILE",
                    "BINARY_DOUBLE",
                    "BINARY_FLOAT",
                    "BINARY_INTEGER",
                    "BLOB",
                    "BOOLEAN",
                    "CHAR",
                    "CHARACTER",
                    "CHARACTER VARYING",
                    "CLOB",
                    "DATE",
                    "DEC",
                    "DECIMAL",
                    "DOUBLE PRECISION",
                    "FLOAT",
                    "INT",
                    "INTEGER",
                    "INTERVAL",
                    "JSON",
                    "LONG",
                    "LONG RAW",
                    "NATIONAL CHAR",
                    "NATIONAL CHAR VARYING",
                    "NATIONAL CHARACTER",
                    "NATIONAL CHARACTER VARYING",
                    "NCHAR",
                    "NCLOB",
                    "NESTED TABLE",
                    "OBJECT",
                    "NUMBER",
                    "NUMERIC",
                    "NVARCHAR2",
                    "PLS_INTEGER",
                    "RAW",
                    "REF",
                    "REAL",
                    "ROWID",
                    "SDO_GEOMETRY",
                    "SMALLINT",
                    "TIMESTAMP",
                    "URITYPE",
                    "UROWID",
                    "VARCHAR",
                    "VARCHAR2",
                    "VARRAY",
                    "VARYING ARRAY",
                    "VECTOR",
                    "XMLTYPE",
                    roles = setOf(DataTypeName),
                ) +
                sourcePatterns(
                    "ACOS",
                    "ASIN",
                    "ATAN",
                    "ATAN2",
                    "AVG",
                    "COALESCE",
                    "COS",
                    "COUNT",
                    "CURRENT_DATE",
                    "CURRENT_TIMESTAMP",
                    "DECODE",
                    "DENSE_RANK",
                    "DOMAIN_DISPLAY",
                    "DOMAIN_NAME",
                    "DOMAIN_ORDER",
                    "EXP",
                    "GREATEST",
                    "HEXTORAW",
                    "INSTR",
                    "JSON_ARRAY",
                    "JSON_ARRAYAGG",
                    "JSON_OBJECT",
                    "JSON_OBJECTAGG",
                    "JSON_QUERY",
                    "JSON_SERIALIZE",
                    "LEAST",
                    "LENGTH",
                    "LISTAGG",
                    "LN",
                    "LOCALTIMESTAMP",
                    "LOG",
                    "MAX",
                    "MEDIAN",
                    "MIN",
                    "NANVL",
                    "NTILE",
                    "NVL",
                    "NVL2",
                    "RANK",
                    "RAWTOHEX",
                    "REGEXP_LIKE",
                    "ROW_NUMBER",
                    "SIN",
                    "SQRT",
                    "STDDEV",
                    "SUM",
                    "SYSDATE",
                    "SYSTIMESTAMP",
                    "TAN",
                    "TO_CHAR",
                    "TO_DATE",
                    "TO_NUMBER",
                    "TO_TIMESTAMP",
                    "TO_TIMESTAMP_TZ",
                    "VARIANCE",
                    "XMLAGG",
                    "XMLELEMENT",
                    "XMLFOREST",
                    "XMLSERIALIZE",
                    "XMLTYPE",
                    roles = setOf(CommonFunctionName),
                ) +
                sourcePatterns(
                    "CONNECT",
                    "MATCH_RECOGNIZE",
                    "MODEL",
                    "PIVOT",
                    "QUALIFY",
                    "UNPIVOT",
                    roles = setOf(AliasBoundary, KeywordCaseTarget),
                ) +
                sourcePatterns("''", roles = setOf(EmptyStringLiteral)),
    )
