package dev.s7a.sqldelight.oracle.check.dialect

import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.AliasBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.ClauseBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.CommonFunctionName
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.DataTypeName
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.GroupByBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.JoinConditionBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.KeywordCaseTarget
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.OrderByBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.PredicateBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.SqlDelightExecutableStatementStart
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.SqlDelightStatementStart
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.StatementStart
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.TableReferenceBoundary
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.TransactionEndStatement
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatternRole.TransactionStartStatement
import dev.s7a.sqldelight.check.api.SqlDialectSourcePatterns
import dev.s7a.sqldelight.check.api.sourcePatterns

/**
 * Conservative source scanner patterns for Oracle Database SQL.
 */
public val OracleDialectSourcePatterns: SqlDialectSourcePatterns =
    SqlDialectSourcePatterns(
        patterns =
            SqlDialectSourcePatterns.SourceScannerDefault.patterns +
                sourcePatterns(
                    "ALTER INDEX",
                    "ALTER DOMAIN",
                    "ALTER MATERIALIZED VIEW",
                    "ALTER MATERIALIZED VIEW LOG",
                    "ALTER MATERIALIZED ZONEMAP",
                    "ALTER ANALYTIC VIEW",
                    "ALTER ASSERTION",
                    "ALTER ATTRIBUTE DIMENSION",
                    "ALTER CLUSTER",
                    "ALTER DATABASE",
                    "ALTER DATABASE DICTIONARY",
                    "ALTER DATABASE LINK",
                    "ALTER DIMENSION",
                    "ALTER DIRECTIVE",
                    "ALTER DISKGROUP",
                    "ALTER FLASHBACK ARCHIVE",
                    "ALTER FUNCTION",
                    "ALTER HIERARCHY",
                    "ALTER INDEXTYPE",
                    "ALTER INMEMORY JOIN GROUP",
                    "ALTER JAVA",
                    "ALTER JSON RELATIONAL DUALITY VIEW",
                    "ALTER LIBRARY",
                    "ALTER LOCKDOWN PROFILE",
                    "ALTER MLE ENV",
                    "ALTER MLE MODULE",
                    "ALTER OPERATOR",
                    "ALTER OUTLINE",
                    "ALTER PACKAGE",
                    "ALTER PLUGGABLE DATABASE",
                    "ALTER PMEM FILESTORE",
                    "ALTER PROCEDURE",
                    "ALTER PROFILE",
                    "ALTER PROPERTY GRAPH",
                    "ALTER RESOURCE COST",
                    "ALTER ROLE",
                    "ALTER ROLLBACK SEGMENT",
                    "ALTER SEQUENCE",
                    "ALTER SESSION",
                    "ALTER SYNONYM",
                    "ALTER SYSTEM",
                    "ALTER TABLE",
                    "ALTER TABLESPACE",
                    "ALTER TABLESPACE SET",
                    "ALTER TRIGGER",
                    "ALTER TYPE",
                    "ALTER USER",
                    "ALTER VIEW",
                    "ADMINISTER KEY MANAGEMENT",
                    "ANALYZE",
                    "ASSOCIATE STATISTICS",
                    "AUDIT",
                    "CALL",
                    "COMMENT",
                    "COMMIT",
                    "CREATE ANALYTIC VIEW",
                    "CREATE APPLICATION IDENTITY",
                    "CREATE ASSERTION",
                    "CREATE ATTRIBUTE DIMENSION",
                    "CREATE AUDIT POLICY",
                    "CREATE CLUSTER",
                    "CREATE CONTEXT",
                    "CREATE CONTROLFILE",
                    "CREATE DATA GRANT",
                    "CREATE DATA ROLE",
                    "CREATE DATABASE LINK",
                    "CREATE DATABASE",
                    "CREATE DIMENSION",
                    "CREATE DIRECTORY",
                    "CREATE DIRECTIVE",
                    "CREATE DISKGROUP",
                    "CREATE DOMAIN",
                    "CREATE EDITION",
                    "CREATE END USER",
                    "CREATE END USER CONTEXT",
                    "CREATE FLEXIBLE DOMAIN",
                    "CREATE FLASHBACK ARCHIVE",
                    "CREATE FUNCTION",
                    "CREATE HIERARCHY",
                    "CREATE HYBRID VECTOR INDEX",
                    "CREATE ICEBERG TABLE",
                    "CREATE INDEX",
                    "CREATE INDEXTYPE",
                    "CREATE INMEMORY JOIN GROUP",
                    "CREATE JAVA",
                    "CREATE JSON RELATIONAL DUALITY VIEW",
                    "CREATE LIBRARY",
                    "CREATE LOCKDOWN PROFILE",
                    "CREATE LOGICAL PARTITION TRACKING",
                    "CREATE MATERIALIZED VIEW",
                    "CREATE MATERIALIZED VIEW LOG",
                    "CREATE MATERIALIZED ZONEMAP",
                    "CREATE MLE ENV",
                    "CREATE MLE MODULE",
                    "CREATE OPERATOR",
                    "CREATE OUTLINE",
                    "CREATE PACKAGE",
                    "CREATE PACKAGE BODY",
                    "CREATE PFILE",
                    "CREATE PLUGGABLE DATABASE",
                    "CREATE PMEM FILESTORE",
                    "CREATE PROCEDURE",
                    "CREATE PROFILE",
                    "CREATE PROPERTY GRAPH",
                    "CREATE RESTORE POINT",
                    "CREATE ROLE",
                    "CREATE ROLLBACK SEGMENT",
                    "CREATE SCHEMA",
                    "CREATE SEQUENCE",
                    "CREATE SPFILE",
                    "CREATE SYNONYM",
                    "CREATE TRIGGER",
                    "CREATE TRUE CACHE",
                    "CREATE TYPE",
                    "CREATE TYPE BODY",
                    "CREATE USER",
                    "CREATE VECTOR INDEX",
                    "CREATE VIEW",
                    "DISASSOCIATE STATISTICS",
                    "DROP ANALYTIC VIEW",
                    "DROP APPLICATION IDENTITY",
                    "DROP ASSERTION",
                    "DROP ATTRIBUTE DIMENSION",
                    "DROP AUDIT POLICY",
                    "DROP CLUSTER",
                    "DROP CONTEXT",
                    "DROP DATA GRANT",
                    "DROP DATA ROLE",
                    "DROP DATABASE LINK",
                    "DROP DATABASE",
                    "DROP DIMENSION",
                    "DROP DIRECTORY",
                    "DROP DIRECTIVE",
                    "DROP DISKGROUP",
                    "DROP EDITION",
                    "DROP END USER",
                    "DROP END USER CONTEXT",
                    "DROP FLASHBACK ARCHIVE",
                    "DROP FUNCTION",
                    "DROP HIERARCHY",
                    "DROP ICEBERG TABLE",
                    "DROP INDEX",
                    "DROP DOMAIN",
                    "DROP INDEXTYPE",
                    "DROP INMEMORY JOIN GROUP",
                    "DROP JAVA",
                    "DROP LIBRARY",
                    "DROP LOCKDOWN PROFILE",
                    "DROP MATERIALIZED VIEW",
                    "DROP MATERIALIZED VIEW LOG",
                    "DROP MATERIALIZED ZONEMAP",
                    "DROP MLE ENV",
                    "DROP MLE MODULE",
                    "DROP OPERATOR",
                    "DROP OUTLINE",
                    "DROP PACKAGE",
                    "DROP PLUGGABLE DATABASE",
                    "DROP PMEM FILESTORE",
                    "DROP PROCEDURE",
                    "DROP PROFILE",
                    "DROP PROPERTY GRAPH",
                    "DROP RESTORE POINT",
                    "DROP ROLE",
                    "DROP ROLLBACK SEGMENT",
                    "DROP SEQUENCE",
                    "DROP SYNONYM",
                    "DROP TABLE",
                    "DROP TABLESPACE",
                    "DROP TABLESPACE SET",
                    "DROP TRIGGER",
                    "DROP TYPE",
                    "DROP TYPE BODY",
                    "DROP USER",
                    "DROP VIEW",
                    "EXPLAIN PLAN",
                    "FLASHBACK",
                    "GRANT",
                    "LOCK TABLE",
                    "MERGE",
                    "PURGE",
                    "RENAME",
                    "REVOKE",
                    "REVOKE DATA ROLE",
                    "ROLLBACK",
                    "SAVEPOINT",
                    "SET CONSTRAINTS",
                    "SET ROLE",
                    "SET TRANSACTION",
                    "SET USE DATA GRANTS ONLY",
                    "TRUNCATE",
                    "TRUNCATE CLUSTER",
                    "UPDATE END USER CONTEXT",
                    roles = setOf(StatementStart, SqlDelightStatementStart),
                ) +
                sourcePatterns(
                    "INSERT ALL",
                    "INSERT FIRST",
                    "MERGE",
                    roles = setOf(SqlDelightExecutableStatementStart),
                ) +
                sourcePatterns("SET TRANSACTION", roles = setOf(TransactionStartStatement)) +
                sourcePatterns("COMMIT", "ROLLBACK", roles = setOf(TransactionEndStatement)) +
                sourcePatterns("CREATE SEQUENCE", roles = setOf(CreateSequenceStatementStart)) +
                sourcePatterns(
                    "AS OF SCN",
                    "AS OF TIMESTAMP",
                    "ADD MEASURES",
                    "ALTER DOMAIN",
                    "ANNOTATIONS",
                    "CHOOSE DOMAIN USING",
                    "CONNECT BY",
                    "COLUMNS",
                    "DEFAULT MEASURE",
                    "DEFAULT ON NULL",
                    "DESTINATION KEY",
                    "DISPLAY",
                    "DIMENSION BY",
                    "EDGE TABLES",
                    "ENUM",
                    "FETCH {FIRST|NEXT} [ROW|ROWS]",
                    "FILTER FACT",
                    "FOR UPDATE",
                    "GRAPH_TABLE",
                    "GROUPS",
                    "HIERARCHIES",
                    "INSERT ALL",
                    "INSERT FIRST",
                    "JSON_TABLE",
                    "LATERAL",
                    "MATCH",
                    "MATCH_RECOGNIZE",
                    "MEASURES",
                    "MODEL",
                    "OFFSET",
                    "ONLY",
                    "ORDER",
                    "PARTITION",
                    "PIVOT",
                    "PROPERTIES",
                    "QUALIFY",
                    "RETURNING",
                    "SAMPLE",
                    "SEARCH",
                    "SHARDS",
                    "SOURCE KEY",
                    "START WITH",
                    "STRICT",
                    "UNPIVOT",
                    "USECASE",
                    "VERTEX TABLES",
                    "VERSIONS BETWEEN",
                    "XMLTABLE",
                    roles = setOf(ClauseBoundary),
                ) +
                sourcePatterns("CONNECT BY", roles = setOf(ConnectByClause)) +
                sourcePatterns("START WITH", roles = setOf(StartWithClause)) +
                sourcePatterns("<->", "<=>", "<#>", roles = setOf(VectorDistanceOperator)) +
                sourcePatterns("FETCH", "FOR", "OFFSET", "RETURNING", roles = setOf(OrderByBoundary)) +
                sourcePatterns(
                    "CONNECT",
                    "FETCH",
                    "FOR",
                    "GRAPH_TABLE",
                    "MATCH",
                    "MODEL",
                    "OFFSET",
                    "RETURNING",
                    "START",
                    roles = setOf(GroupByBoundary, PredicateBoundary, JoinConditionBoundary),
                ) +
                sourcePatterns("CONNECT", "FETCH", "FOR", "MODEL", "OFFSET", "START", roles = setOf(TableReferenceBoundary)) +
                sourcePatterns(
                    "ANYDATA",
                    "ANYDATASET",
                    "ANYTYPE",
                    "BFILE",
                    "BINARY_DOUBLE",
                    "BINARY_FLOAT",
                    "BINARY_INTEGER",
                    "BLOB",
                    "BOOLEAN",
                    "CHAR",
                    "CHARACTER",
                    "CHARACTER VARYING",
                    "CLOB",
                    "DATE",
                    "DEC",
                    "DECIMAL",
                    "DBURITYPE",
                    "DOUBLE PRECISION",
                    "FLOAT",
                    "HTTPURITYPE",
                    "INT",
                    "INTEGER",
                    "INTERVAL",
                    "JSON",
                    "LONG",
                    "LONG RAW",
                    "NATIONAL CHAR",
                    "NATIONAL CHAR VARYING",
                    "NATIONAL CHARACTER",
                    "NATIONAL CHARACTER VARYING",
                    "NCHAR",
                    "NCLOB",
                    "NESTED TABLE",
                    "OBJECT",
                    "NUMBER",
                    "NUMERIC",
                    "NVARCHAR2",
                    "PLS_INTEGER",
                    "RAW",
                    "REF",
                    "REAL",
                    "ROWID",
                    "SDO_GEORASTER",
                    "SDO_GEOMETRY",
                    "SDO_TOPO_GEOMETRY",
                    "SMALLINT",
                    "TIMESTAMP",
                    "URITYPE",
                    "UROWID",
                    "VARCHAR",
                    "VARCHAR2",
                    "VARRAY",
                    "VARYING ARRAY",
                    "VECTOR",
                    "XMLTYPE",
                    roles = setOf(DataTypeName),
                ) +
                sourcePatterns(
                    "ABS",
                    "ACOS",
                    "ADD_MONTHS",
                    "APPROX_COUNT",
                    "APPROX_COUNT_DISTINCT",
                    "APPROX_MEDIAN",
                    "APPROX_PERCENTILE",
                    "APPROX_SUM",
                    "ASIN",
                    "ASCII",
                    "ASCIISTR",
                    "ATAN",
                    "ATAN2",
                    "AVG",
                    "BFILENAME",
                    "BIN_TO_NUM",
                    "BITAND",
                    "BIT_AND_AGG",
                    "BIT_OR_AGG",
                    "BIT_XOR_AGG",
                    "BOOLEAN_AND_AGG",
                    "BOOLEAN_OR_AGG",
                    "CALENDAR_ADD_DAYS",
                    "CALENDAR_ADD_MONTHS",
                    "CALENDAR_ADD_QUARTERS",
                    "CALENDAR_ADD_WEEKS",
                    "CALENDAR_ADD_YEARS",
                    "CALENDAR_DAY",
                    "CALENDAR_DAY_OF_MONTH",
                    "CALENDAR_DAY_OF_QUARTER",
                    "CALENDAR_DAY_OF_WEEK",
                    "CALENDAR_DAY_OF_YEAR",
                    "CALENDAR_MONTH",
                    "CALENDAR_MONTH_END_DATE",
                    "CALENDAR_MONTH_OF_QUARTER",
                    "CALENDAR_MONTH_OF_YEAR",
                    "CALENDAR_MONTH_START_DATE",
                    "CALENDAR_QUARTER",
                    "CALENDAR_QUARTER_END_DATE",
                    "CALENDAR_QUARTER_OF_YEAR",
                    "CALENDAR_QUARTER_START_DATE",
                    "CALENDAR_SINCE",
                    "CALENDAR_WEEK",
                    "CALENDAR_WEEK_END_DATE",
                    "CALENDAR_WEEK_OF_YEAR",
                    "CALENDAR_WEEK_START_DATE",
                    "CALENDAR_YEAR",
                    "CALENDAR_YEAR_END_DATE",
                    "CALENDAR_YEAR_NUMBER",
                    "CALENDAR_YEAR_START_DATE",
                    "CARDINALITY",
                    "CHECKSUM",
                    "CEIL",
                    "CHARTOROWID",
                    "CHR",
                    "COALESCE",
                    "CLUSTER_DETAILS",
                    "CLUSTER_DISTANCE",
                    "CLUSTER_ID",
                    "CLUSTER_PROBABILITY",
                    "CLUSTER_SET",
                    "COLLATION",
                    "COLLECT",
                    "COMPOSE",
                    "CONCAT",
                    "CON_DBID_TO_ID",
                    "CON_GUID_TO_ID",
                    "CON_NAME_TO_ID",
                    "CON_UID_TO_ID",
                    "CONVERT",
                    "COS",
                    "COSH",
                    "CORR",
                    "COVAR_POP",
                    "COVAR_SAMP",
                    "COUNT",
                    "CURRENT_DATE",
                    "CURRENT_TIMESTAMP",
                    "CUME_DIST",
                    "CV",
                    "DECODE",
                    "DECOMPOSE",
                    "DENSE_RANK",
                    "DEREF",
                    "DOMAIN_CHECK",
                    "DOMAIN_CHECK_TYPE",
                    "DOMAIN_DISPLAY",
                    "DOMAIN_NAME",
                    "DOMAIN_ORDER",
                    "DUMP",
                    "EMPTY_BLOB",
                    "EMPTY_CLOB",
                    "EXP",
                    "EXTRACT",
                    "FEATURE_COMPARE",
                    "FEATURE_DETAILS",
                    "FEATURE_ID",
                    "FEATURE_SET",
                    "FEATURE_VALUE",
                    "FISCAL_ADD_DAYS",
                    "FISCAL_ADD_MONTHS",
                    "FISCAL_ADD_QUARTERS",
                    "FISCAL_ADD_WEEKS",
                    "FISCAL_ADD_YEARS",
                    "FISCAL_DAY",
                    "FISCAL_DAY_OF_MONTH",
                    "FISCAL_DAY_OF_QUARTER",
                    "FISCAL_DAY_OF_WEEK",
                    "FISCAL_DAY_OF_YEAR",
                    "FISCAL_MONTH",
                    "FISCAL_MONTH_END_DATE",
                    "FISCAL_MONTH_OF_QUARTER",
                    "FISCAL_MONTH_OF_YEAR",
                    "FISCAL_MONTH_START_DATE",
                    "FISCAL_QUARTER",
                    "FISCAL_QUARTER_END_DATE",
                    "FISCAL_QUARTER_OF_YEAR",
                    "FISCAL_QUARTER_START_DATE",
                    "FISCAL_WEEK",
                    "FISCAL_WEEK_END_DATE",
                    "FISCAL_WEEK_OF_YEAR",
                    "FISCAL_WEEK_START_DATE",
                    "FISCAL_YEAR",
                    "FISCAL_YEAR_END_DATE",
                    "FISCAL_YEAR_NUMBER",
                    "FISCAL_YEAR_START_DATE",
                    "FIRST_VALUE",
                    "FLOOR",
                    "FROM_TZ",
                    "FROM_VECTOR",
                    "FUZZY_MATCH",
                    "GREATEST",
                    "HAMMING_DISTANCE",
                    "HEXTORAW",
                    "INITCAP",
                    "INSTR",
                    "INNER_PRODUCT",
                    "IS_UUID",
                    "ITERATION_NUMBER",
                    "JACCARD_DISTANCE",
                    "JSON",
                    "JSON_ARRAY",
                    "JSON_ARRAYAGG",
                    "JSON_DATAGUIDE",
                    "JSON_ID",
                    "JSON_MERGEPATCH",
                    "JSON_OBJECT",
                    "JSON_OBJECTAGG",
                    "JSON_QUERY",
                    "JSON_SCALAR",
                    "JSON_SERIALIZE",
                    "JSON_TRANSFORM",
                    "JSON_VALUE",
                    "KURTOSIS_POP",
                    "KURTOSIS_SAMP",
                    "L1_DISTANCE",
                    "L2_DISTANCE",
                    "LAG",
                    "LAST_VALUE",
                    "LAST_DAY",
                    "LEAST",
                    "LEAD",
                    "LENGTH",
                    "LISTAGG",
                    "LN",
                    "LNNVL",
                    "LOCALTIMESTAMP",
                    "LOG",
                    "LOWER",
                    "LPAD",
                    "LTRIM",
                    "MAKE_REF",
                    "MAX",
                    "MEDIAN",
                    "MIN",
                    "MOD",
                    "MONTHS_BETWEEN",
                    "NANVL",
                    "NCHR",
                    "NLS_CHARSET_DECL_LEN",
                    "NLS_CHARSET_ID",
                    "NLS_CHARSET_NAME",
                    "NLS_COLLATION_ID",
                    "NLS_COLLATION_NAME",
                    "NEXT_DAY",
                    "NLS_INITCAP",
                    "NLS_LOWER",
                    "NLS_UPPER",
                    "NLSSORT",
                    "NEW_TIME",
                    "NTH_VALUE",
                    "NTILE",
                    "NUMTODSINTERVAL",
                    "NUMTOYMINTERVAL",
                    "NVL",
                    "NVL2",
                    "NULLIF",
                    "ORA_DM_PARTITION_NAME",
                    "ORA_DST_AFFECTED",
                    "ORA_DST_CONVERT",
                    "ORA_DST_ERROR",
                    "ORA_HASH",
                    "ORA_INVOKING_USER",
                    "ORA_INVOKING_USERID",
                    "PHONIC_ENCODE",
                    "PRESENTNNV",
                    "PRESENTV",
                    "PREVIOUS",
                    "PREDICTION",
                    "POWERMULTISET",
                    "POWERMULTISET_BY_CARDINALITY",
                    "PREDICTION_BOUNDS",
                    "PREDICTION_COST",
                    "PREDICTION_DETAILS",
                    "PREDICTION_PROBABILITY",
                    "PREDICTION_SET",
                    "PERCENT_RANK",
                    "PERCENTILE_CONT",
                    "PERCENTILE_DISC",
                    "RANK",
                    "RATIO_TO_REPORT",
                    "RAW_TO_UUID",
                    "RAWTOHEX",
                    "RAWTONHEX",
                    "REF",
                    "REGEXP_LIKE",
                    "REGEXP_REPLACE",
                    "REGEXP_SUBSTR",
                    "REMAINDER",
                    "RETAIL_ADD_DAYS",
                    "RETAIL_ADD_MONTHS",
                    "RETAIL_ADD_QUARTERS",
                    "RETAIL_ADD_WEEKS",
                    "RETAIL_ADD_YEARS",
                    "RETAIL_DAY",
                    "RETAIL_DAY_EXISTS",
                    "RETAIL_DAY_OF_MONTH",
                    "RETAIL_DAY_OF_QUARTER",
                    "RETAIL_DAY_OF_WEEK",
                    "RETAIL_DAY_OF_YEAR",
                    "RETAIL_MONTH",
                    "RETAIL_MONTH_END_DATE",
                    "RETAIL_MONTH_OF_QUARTER",
                    "RETAIL_MONTH_OF_YEAR",
                    "RETAIL_MONTH_START_DATE",
                    "RETAIL_QUARTER",
                    "RETAIL_QUARTER_END_DATE",
                    "RETAIL_QUARTER_OF_YEAR",
                    "RETAIL_QUARTER_START_DATE",
                    "RETAIL_WEEK",
                    "RETAIL_WEEK_END_DATE",
                    "RETAIL_WEEK_OF_MONTH",
                    "RETAIL_WEEK_OF_QUARTER",
                    "RETAIL_WEEK_OF_YEAR",
                    "RETAIL_WEEK_START_DATE",
                    "RETAIL_YEAR",
                    "RETAIL_YEAR_END_DATE",
                    "RETAIL_YEAR_NUMBER",
                    "RETAIL_YEAR_START_DATE",
                    "RPAD",
                    "ROW_NUMBER",
                    "ROUND",
                    "ROWIDTOCHAR",
                    "ROWIDTONCHAR",
                    "RTRIM",
                    "SCN_TO_TIMESTAMP",
                    "SIGN",
                    "SIN",
                    "SINH",
                    "SKEWNESS_POP",
                    "SKEWNESS_SAMP",
                    "SOUNDEX",
                    "SQRT",
                    "STANDARD_HASH",
                    "STDDEV",
                    "STDDEV_POP",
                    "STDDEV_SAMP",
                    "SET",
                    "SUM",
                    "SYSDATE",
                    "SYSTIMESTAMP",
                    "SYS_CONTEXT",
                    "SYS_GUID",
                    "SYS_CONNECT_BY_PATH",
                    "SYS_EXTRACT_UTC",
                    "SYS_TYPEID",
                    "TAN",
                    "TANH",
                    "TRANSLATE",
                    "TRIM",
                    "TRUNC",
                    "TO_CHAR",
                    "TO_BINARY_DOUBLE",
                    "TO_BINARY_FLOAT",
                    "TO_BLOB",
                    "TO_CLOB",
                    "TO_DATE",
                    "TO_DSINTERVAL",
                    "TO_LOB",
                    "TO_MULTI_BYTE",
                    "TO_NCHAR",
                    "TO_NCLOB",
                    "TO_NUMBER",
                    "TO_SINGLE_BYTE",
                    "TO_TIMESTAMP",
                    "TO_TIMESTAMP_TZ",
                    "TO_VECTOR",
                    "TO_YMINTERVAL",
                    "TZ_OFFSET",
                    "UUID",
                    "UUID_TO_RAW",
                    "UPPER",
                    "UNISTR",
                    "USERENV",
                    "VALIDATE_CONVERSION",
                    "VARIANCE",
                    "VAR_POP",
                    "VAR_SAMP",
                    "VECTOR",
                    "VECTOR_CHUNKS",
                    "VECTOR_DIMS",
                    "VECTOR_DIMENSION_COUNT",
                    "VECTOR_DIMENSION_FORMAT",
                    "VECTOR_DISTANCE",
                    "VECTOR_EMBEDDING",
                    "VECTOR_NORM",
                    "VECTOR_SERIALIZE",
                    "VSIZE",
                    "WIDTH_BUCKET",
                    "XMLAGG",
                    "XMLELEMENT",
                    "XMLFOREST",
                    "XMLQUERY",
                    "XMLSERIALIZE",
                    "XMLTYPE",
                    roles = setOf(CommonFunctionName),
                ) +
                sourcePatterns(
                    "CONNECT",
                    "MATCH_RECOGNIZE",
                    "MODEL",
                    "PIVOT",
                    "QUALIFY",
                    "UNPIVOT",
                    roles = setOf(AliasBoundary, KeywordCaseTarget),
                ) +
                sourcePatterns("''", roles = setOf(EmptyStringLiteral)),
    )
