package dev.s7a.sqldelight.oracle

import app.cash.sqldelight.core.SqlDelightCompilationUnit
import app.cash.sqldelight.core.SqlDelightDatabaseName
import app.cash.sqldelight.core.SqlDelightDatabaseProperties
import app.cash.sqldelight.core.SqlDelightEnvironment
import app.cash.sqldelight.core.SqlDelightSourceFolder
import app.cash.sqldelight.core.annotators.OptimisticLockCompilerAnnotator
import app.cash.sqldelight.core.lang.MigrationLanguage
import app.cash.sqldelight.core.lang.SqlDelightLanguage
import app.cash.sqldelight.core.lang.SqlDelightQueriesFile
import com.alecstrong.sql.psi.core.SqlAnnotationHolder
import com.intellij.lang.LanguageParserDefinitions
import com.intellij.psi.PsiDocumentManager
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import java.io.File
import java.nio.file.Files

class OracleParserBackedTest :
    FunSpec({
        test("parses Oracle create table type names through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE sample (
                  id NUMBER(10) NOT NULL,
                  amount NUMBER(10, 2),
                  name NATIONAL CHARACTER VARYING(100),
                  payload JSON,
                  raw_uuid RAW(16),
                  embedding VECTOR(3, FLOAT32),
                  created_at TIMESTAMP(6) WITH LOCAL TIME ZONE,
                  elapsed INTERVAL DAY TO SECOND
                );

                selectAll:
                SELECT id, amount, name, payload, raw_uuid, embedding, created_at, elapsed
                FROM sample;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle inline column constraints through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE accounts (
                  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                  external_id VARCHAR2(64) CONSTRAINT accounts_external_id_unique UNIQUE ENABLE NOVALIDATE,
                  status VARCHAR2(16) DEFAULT 'ACTIVE' NOT NULL,
                  archived_at TIMESTAMP INVISIBLE,
                  parent_id NUMBER REFERENCES accounts(id) DEFERRABLE INITIALLY DEFERRED
                );

                selectAll:
                SELECT id, external_id, status, archived_at, parent_id
                FROM accounts;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle table constraints through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE account_events (
                  account_id NUMBER NOT NULL,
                  event_id NUMBER NOT NULL,
                  parent_event_id NUMBER,
                  event_type VARCHAR2(64) NOT NULL,
                  event_payload JSON,
                  CONSTRAINT account_events_pk PRIMARY KEY (account_id, event_id) ENABLE,
                  CONSTRAINT account_events_type_unique UNIQUE (account_id, event_type) DEFERRABLE INITIALLY IMMEDIATE,
                  CONSTRAINT account_events_payload_check CHECK (event_payload IS NOT NULL) NOVALIDATE,
                  CONSTRAINT account_events_parent_fk FOREIGN KEY (account_id, parent_event_id) REFERENCES account_events(account_id, event_id) DEFERRABLE INITIALLY DEFERRED
                );

                selectAll:
                SELECT account_id, event_id, parent_event_id, event_type, event_payload
                FROM account_events;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create table statement variants through SQLDelight environment exactly") {
            val sql =
                """
                CREATE GLOBAL TEMPORARY TABLE IF NOT EXISTS staged_accounts (
                  account_id NUMBER NOT NULL,
                  external_id VARCHAR2(64),
                  CONSTRAINT staged_accounts_pk PRIMARY KEY (account_id)
                ) ON COMMIT PRESERVE ROWS;

                CREATE PRIVATE TEMPORARY TABLE private_staged_accounts (
                  account_id NUMBER NOT NULL,
                  external_id VARCHAR2(64)
                ) ON COMMIT DELETE ROWS;

                CREATE TABLE account_snapshot AS
                SELECT account_id, external_id
                FROM staged_accounts;

                selectAll:
                SELECT account_id, external_id
                FROM account_snapshot;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle alter table statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE alter_targets (
                  id NUMBER PRIMARY KEY,
                  status VARCHAR2(16)
                );

                ALTER TABLE alter_targets ADD created_at TIMESTAMP;
                ALTER TABLE alter_targets ADD (
                  updated_at TIMESTAMP,
                  archived_at TIMESTAMP INVISIBLE
                );
                ALTER TABLE alter_targets ADD CONSTRAINT alter_targets_status_check CHECK (status IS NOT NULL) ENABLE;
                ALTER TABLE alter_targets MODIFY (
                  created_at TIMESTAMP NOT NULL,
                  updated_at TIMESTAMP NOT NULL
                );
                ALTER TABLE alter_targets MODIFY status VARCHAR2(32) NOT NULL;
                ALTER TABLE alter_targets RENAME COLUMN status TO account_status;
                ALTER TABLE alter_targets DROP COLUMN archived_at CASCADE CONSTRAINTS;
                ALTER TABLE alter_targets DROP COLUMN created_at CASCADE CONSTRAINTS;
                ALTER TABLE alter_targets DROP CONSTRAINT alter_targets_status_check;
                """.trimIndent()

            parseOracleSql(sql, fileName = "1.sqm") shouldBe
                ParseResult(
                    fileNames = emptyList(),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create index statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE indexed_accounts (
                  id NUMBER PRIMARY KEY,
                  status VARCHAR2(32) NOT NULL,
                  created_at TIMESTAMP,
                  archived_at TIMESTAMP
                );

                CREATE UNIQUE INDEX IF NOT EXISTS indexed_accounts_status_idx
                ON indexed_accounts (status) VISIBLE ONLINE;

                CREATE BITMAP INDEX indexed_accounts_archive_idx
                ON indexed_accounts (archived_at, created_at) INVISIBLE NOLOGGING;

                CREATE INDEX indexed_accounts_created_idx
                ON indexed_accounts (created_at DESC) REVERSE COMPUTE STATISTICS;

                CREATE INDEX indexed_accounts_status_upper_idx
                ON indexed_accounts (UPPER(status));

                selectAll:
                SELECT id, status, created_at, archived_at
                FROM indexed_accounts;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("parses Oracle create view statements through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE view_accounts (
                  id NUMBER PRIMARY KEY,
                  status VARCHAR2(32) NOT NULL,
                  created_at TIMESTAMP
                );

                CREATE OR REPLACE FORCE EDITIONING VIEW account_status_view AS
                SELECT id AS account_id, status AS account_status, created_at AS account_created_at
                FROM view_accounts
                WHERE status IS NOT NULL
                BEQUEATH CURRENT_USER
                WITH CHECK OPTION;

                CREATE NO FORCE VIEW readonly_account_view AS
                SELECT id, status
                FROM view_accounts
                WITH READ ONLY;

                selectAll:
                SELECT account_id, account_status, account_created_at
                FROM account_status_view;
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors = emptyList(),
                )
        }

        test("reports malformed Oracle SQL through SQLDelight environment exactly") {
            val sql =
                """
                CREATE TABLE sample (
                  id NUMBER(10),
                  name VARCHAR2(100)
                """.trimIndent()

            parseOracleSql(sql) shouldBe
                ParseResult(
                    fileNames = listOf("Test.sq"),
                    errors =
                        listOf(
                            "Test.sq: (3, 20): ')', ',', <column constraint real> or AS expected",
                        ),
                )
        }
    })

private data class ParseResult(
    val fileNames: List<String>,
    val errors: List<String>,
)

private fun parseOracleSql(
    sql: String,
    fileName: String = "Test.sq",
): ParseResult {
    val root = Files.createTempDirectory("sqldelight-oracle-parser-test").toFile()
    val sourceDirectory = File(root, "com/example").apply { mkdirs() }
    File(sourceDirectory, fileName).writeText(sql)

    val errors = mutableListOf<String>()
    val compilationUnit = OracleParserTestCompilationUnit(File(root, "output"))
    val environment =
        SqlDelightEnvironment(
            sourceFolders = listOf(root),
            dependencyFolders = emptyList(),
            properties = OracleParserTestDatabaseProperties(root, compilationUnit),
            dialect = OracleDialect(),
            verifyMigrations = true,
            moduleName = "oracle-parser-test",
            compilationUnit = compilationUnit,
        )

    LanguageParserDefinitions.INSTANCE.forLanguage(SqlDelightLanguage).createParser(environment.project)
    LanguageParserDefinitions.INSTANCE.forLanguage(MigrationLanguage).createParser(environment.project)
    environment.annotate(listOf(OptimisticLockCompilerAnnotator()), createAnnotationHolder(errors))

    val fileNames = mutableListOf<String>()
    environment.forSourceFiles { psiFile ->
        if (psiFile is SqlDelightQueriesFile) {
            fileNames += psiFile.name
        }
    }

    return ParseResult(
        fileNames = fileNames.sorted(),
        errors = errors,
    )
}

private data class OracleParserTestCompilationUnit(
    override val outputDirectoryFile: File,
) : SqlDelightCompilationUnit {
    override val name: String = "test"
    override val sourceFolders: Set<SqlDelightSourceFolder> = emptySet()
}

private data class OracleParserTestDatabaseProperties(
    override val rootDirectory: File,
    private val compilationUnit: SqlDelightCompilationUnit,
) : SqlDelightDatabaseProperties {
    override val packageName: String = "com.example"
    override val className: String = "TestDatabase"
    override val dependencies: List<SqlDelightDatabaseName> = emptyList()
    override val compilationUnits: List<SqlDelightCompilationUnit> = listOf(compilationUnit)
    override val deriveSchemaFromMigrations: Boolean = false
    override val generateAsync: Boolean = false
    override val expandSelectStar: Boolean = true
    override val treatNullAsUnknownForEquality: Boolean = false
}

private fun createAnnotationHolder(errors: MutableList<String>): SqlAnnotationHolder =
    SqlAnnotationHolder { element, message ->
        val documentManager = PsiDocumentManager.getInstance(element.project)
        val document = requireNotNull(documentManager.getDocument(element.containingFile))
        val lineNumber = document.getLineNumber(element.textOffset)
        val offsetInLine = element.textOffset - document.getLineStartOffset(lineNumber)
        errors += "${element.containingFile.name}: (${lineNumber + 1}, $offsetInLine): $message"
    }
