package dev.s7a.sqldelight.oracle.check.rule.rules

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe

class PreferIdentityColumnRuleTest :
    FunSpec({
        test("reports sequence-trigger generated keys") {
            val diagnostics =
                PreferIdentityColumnRule().diagnostics(
                    """
                    CREATE SEQUENCE customer_id_seq;

                    CREATE TRIGGER customer_id_trigger
                    BEFORE INSERT ON customer
                    FOR EACH ROW
                    BEGIN
                        SELECT customer_id_seq.NEXTVAL INTO :NEW.id FROM dual;
                    END;
                    """,
                )

            diagnostics.summaries() shouldBe
                listOf(
                    DiagnosticSummary(
                        message = PREFER_IDENTITY_MESSAGE,
                        startLine = 3,
                        startColumn = 1,
                        endLine = 3,
                        endColumn = 15,
                    ),
                )
        }

        test("accepts identity columns") {
            PreferIdentityColumnRule().diagnostics(
                """
                CREATE TABLE customer (
                    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY
                );
                """,
            ) shouldBe emptyList()
        }

        test("accepts trigger without local sequence declaration") {
            PreferIdentityColumnRule().diagnostics(
                """
                CREATE TRIGGER customer_audit_trigger
                AFTER INSERT ON customer
                FOR EACH ROW
                BEGIN
                    INSERT INTO customer_audit (customer_id) VALUES (:NEW.id);
                END;
                """,
            ) shouldBe emptyList()
        }

        test("accepts audit trigger that does not assign sequence values to new rows") {
            PreferIdentityColumnRule().diagnostics(
                """
                CREATE SEQUENCE customer_audit_seq;

                CREATE TRIGGER customer_audit_trigger
                AFTER INSERT ON customer
                FOR EACH ROW
                BEGIN
                    INSERT INTO customer_audit (audit_id, customer_id)
                    VALUES (customer_audit_seq.NEXTVAL, :NEW.id);
                END;
                """,
            ) shouldBe emptyList()
        }

        test("ignores sequence-trigger text in comments and string literals") {
            PreferIdentityColumnRule().diagnostics(
                """
                -- CREATE SEQUENCE customer_id_seq;
                /* CREATE SEQUENCE customer_id_seq; */
                SELECT /*+ RESULT_CACHE */ 'CREATE TRIGGER t BEFORE INSERT BEGIN SELECT s.NEXTVAL INTO :NEW.id FROM dual; END;' AS sql_text
                FROM dual;
                """,
            ) shouldBe emptyList()
        }

        test("ignores sequence-trigger text in multiline block comments") {
            PreferIdentityColumnRule().diagnostics(
                """
                /*
                  CREATE SEQUENCE customer_id_seq;
                  CREATE TRIGGER customer_id_trigger
                    BEFORE INSERT ON customer
                    FOR EACH ROW
                    BEGIN
                      SELECT customer_id_seq.NEXTVAL INTO :NEW.id FROM dual;
                    END;
                */
                SELECT 'CREATE SEQUENCE customer_id_seq' AS sql_text
                FROM dual;
                """,
            ) shouldBe emptyList()
        }
    })

private const val PREFER_IDENTITY_MESSAGE =
    "Prefer an Oracle identity column over sequence-trigger generated keys."
