name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release-check:
    name: Release check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6.2.0

      - name: Release check
        run: ./gradlew releaseCheck --stacktrace

  qodana:
    name: Qodana
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Qodana
        uses: JetBrains/qodana-action@v2026.1.3
